### ISSUE TITLE
Implement elimination ballots for two-team formats

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1003]
In two-team formats' elimination rounds, scores may not be attributed, similarly to BP elimination rounds. While BP a checkbox ballot form, a similar form should be added for other formats.

Consensus ballots would be simpler, as most of the BP elimination ballot logic could be re-used (it could also be a solution to #527. Voting ballots are trickier, and could require something akin to a new `TeamScoreByAdj` table to hold who voted how.

The form required could also be integrated with scores for #643.

**Comment by czlee** [comment]
More generally, you can get entire tournaments where (even in inrounds) judges only give results, not speaker scores, and it's long been a low-priority idea to complete refactoring of the scoresheets system to allow for this. Just a heads-up, though—while result.py and scoresheet.py themselves are (iirc) refactored to support new ballot types easily, other parts of the code are not, which is why I've been holding off doing this, tied/low-point wins, and BP grand final results 🙂

I'm in principle fine with adding a `TeamScoreByAdj` model if it's necessary to record this kind of thing. If I remember right, it is—one thing though, we need to be clear in our minds which model fields are primary sources of information, and which are just calculated from other fields.

**Comment by tienne-B** [comment]
Honestly, I still don't really understand `scoresheet.py` :( That's part of why I did not bother with it when adding `.as_dicts()` in the associated PR. Here, it might be to change `DeclaredWinnerMixin` to take a list of winning sides, and its use in two-team formats to raise an error if both are selected. There are classes for tied/low-point wins though, and so it does seem refactored.

I wonder what parts of the code do not readily support these alternative ballots?

To reduce the `TeamScoreByAdj` table, we could remove `margin` and `score` as they are based on the speaker scores of which could be compared by adjudicator separately. However, should the table be populated with per-adjudicator scoresheets?

**Comment by tienne-B** [comment]
It's been a while, but I figured out `scoresheet.py`!

> I wonder what parts of the code [would] not readily support these alternative ballots?
@czlee: Wondering on this question. #1004 up to 1f9fde6 works well in my testing and live (or I don't remember where it fails). So the changes work well with elimination ballots. Any other considerations for formats requiring `TeamScoreByAdj`?

Should `TeamScoreByAdj` be populated for all voting formats, or just for formats requiring it? I'm leaning towards the former, but that would increase the number of rows used up.

**Comment by czlee** [comment]
> It's been a while, but I figured out `scoresheet.py`!

Yay! Great work! Sorry I didn't get to this in time.

> @czlee: Wondering on this question. #1004 up to [1f9fde6](https://github.com/TabbycatDebate/tabbycat/commit/1f9fde6987ddcc52501f7d2367f2b992e31cdcc4) works well in my testing and live (or I don't remember where it fails). So the changes work well with elimination ballots. Any other considerations for formats requiring `TeamScoreByAdj`?

What I had in mind was mostly the forms and tooltips. Since you've implemented it as a one-team-advancing version of the BP elimination round ballot, the forms bit hasn't really affected you. But to give some idea:
- Not for this, but for tie-point wins, the form would need to show a field asking for the winner (since it can't be inferred from scores). Actually, ideally it would do this for score-only ballots too (rather than two checkboxes), but as a first implementation what you've done is fine as it is.
- Tooltips would have to know whether to show scores. (Currently we do this by checking whether the `score is None`. I sort of prefer to choose whether to show scores based on the expected result type, not whether `score is None`.)

Perhaps more importantly, the major refactor I never did was to unify the code that governs (1) how results are structured in the database (a.k.a. `result.py` and `scoresheet.py`), (2) which form is rendered and (3) how results are displayed in various places ("latest results" ticker on admin home, result table tooltips, result icons in tables). Right now, each element is responsible for figuring out itself what it should do based on tournament preferences. This makes for a giant mess of DRY violations. I was prepared to take on the technical debt to get BP out the door, but intended to draw the line there, which is why I never implemented BP grand finals. The logic for understanding what "result type" is used—based on tournament preferences and the current round—should really be in one place, or at least as few places in possible.

> Should `TeamScoreByAdj` be populated for all voting formats, or just for formats requiring it? I'm leaning towards the former, but that would increase the number of rows used up.

To be honest, I don't know. Normally my policy is to populate all redundant fields to make lookups more efficient and permit user overrides (since database lookups are what's used in result display, standings and draw generation), **but** to ignore all redundant fields in the `DebateResult` classes (and hence overwrite redundant fields when resaving a result).

But in this case, `TeamScoreByAdj` wouldn't be used for anything else, so I'd definitely entertain the possibility that it might be better not to store it at all unless it's actually the canonical source.

(Unless we decide to reimplement `NumberOfAdjudicatorsMetricAnnotator` to get rid of the `votes_given` and `votes_possible` fields, by replacing this code with a clever aggregation over `TeamScoreByAdj.win`. But I don't know that this is a good idea.)
https://github.com/TabbycatDebate/tabbycat/blob/4154740182a2fcaa70021419cd9327990c980b22/tabbycat/standings/teams.py#L252-L255
