### ISSUE TITLE
Who-beat-whom standings criterion factors outrounds

### ISSUE THREAD

**Issue by viranw** [TabbycatDebate/tabbycat#1073]
If two teams who would be subject to WBW face each other in the outrounds, the result of that debate is factored into the WBW calculation used for breaks and the team tab, which is probably not expected behaviour (though maybe there are other cases where this behaviour _would_ be expected that I haven't thought of?)

**Comment by czlee** [comment]
It's not expected behaviour, nice catch 🙂

These lines should filter for `debate_team__debate__round__stage=Round.STAGE_PRELIMINARY`:
https://github.com/TabbycatDebate/tabbycat/blob/fbdabf141d9e39c049fb3234159296abba287437/tabbycat/standings/teams.py#L303-L312

And we should add a unit test to check for this.
