### ISSUE TITLE
Adj score bulk-updater appears to be broken

### ISSUE THREAD

**Issue by viranweerasekera** [TabbycatDebate/tabbycat#1096]
Whenever a bulk-update is attempted on a 2.3 dev site there appears to be a 500 error - I think Sentry is reporting on the issue?

**Comment by tienne-B** [comment]
Sentry issue: [BACKEND-1DE](https://sentry.io/organizations/tabbycat-ig/issues/973024236/?referrer=github_plugin)

**Comment by philipbelesky** [comment]
Yea, I think we just never tested the bulk-updater using names rather than ID values. The nested `try`s  here is not super elegant, but it seems to catch both the current set of exceptions and account for the two different methods. I guess if you name your adjudicators as digits that could cause an issue, but I'm not sure that is worth worrying about.
