### ISSUE TITLE
Ballots form doesn't save selected vetoes when enable_motions is false

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#1125]
This affects both the new and old form, so I assume it is in the form logic. I'm not sure there's any reason why you would have this particular combination of preferences set but it might be worth accounting for.

**Comment by tienne-B** [comment]
Seems to be the normal case, as having both `motion_vetoes_enabled` and `enable_motions` enabled is in the Australs and Easters (both) presets. Only UADC has one but not the other.

**Comment by czlee** [comment]
Wait, I'm confused, what's the expected behavior? I think what should happen is: `motion_vetoes_enabled` should cause the ballots form to save motions, and `enable_motions` should have no effect on motion vetoes. But I'm not sure, maybe in days gone past we used to make it so that `motion_vetoes_enabled` and `enable_motions` _both_ had to be enabled for vetoes to work, or something like that.

Or do you mean when `enable_motions` is _not_ set, and when `motion_vetoes_enabled` is set? I had a quick look at the code in results/forms.py. Do you know whether it's that it doesn't save to the database _at all_, or whether it's in the database but just doesn't get loaded as initial data when you try to edit the result?

Possibly relevant code if my guess is right, totally off-track if I interpreted or guessed wrong:
https://github.com/TabbycatDebate/tabbycat/blob/bd30b23530cd2cd56669dfa80ed4a8863dc81a19/tabbycat/results/forms.py#L373-L382

**Comment by philipbelesky** [comment]
Sorry yes, this is the case when `enable_motions` is false but `motion_vetoes_enabled` is true. In that case it turns out the relevant `debateteammotionpreference` records get saved; they just aren't populated into the form when it is viewed again.

**Comment by czlee** [comment]
Okay. The problem is in the code snipper above, lines 378-382 should be conditioned on `self.using_vetoes`, not `self.using_motions`. I'm a bit snowed under with settling in at the moment, but I'll do it if no-one else gets there first. We should add a unit test for this, just to start off the habit.
