### ISSUE TITLE
New venue allocation window formatting bug

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1175]
Running the latest develop version of Tabbycat (2.3.0A) has a minor visual bug on the new venue allocation interface, whereby some debates don't have a line between them (i.e. between St Cuthbert's 5 v Kings 3 and Mount Roskill 1 v Diocesan 2). This was also visible prior to auto venue allocation. 

![image](https://user-images.githubusercontent.com/3196468/62781856-fcfdbd80-bb0c-11e9-9d04-0275ff323cdf.png)

**Comment by philipbelesky** [comment]
Hey, thanks for bringing this to our attention. I haven't been able to replicate this, and there are seemingly none of the normal issues that might cause something like this (i.e. an overly-long line). Let me know if it comes up again in future rounds, otherwise I'll try and keep an eye out for what might trigger this problem.

**Comment by philipbelesky** [comment]
Closing as I haven't found any way to reliably replicate this, but if it comes up again/reliably then let me know.
