### ISSUE TITLE
Sentry SDK

### ISSUE THREAD

**Issue by nickdbush** [TabbycatDebate/tabbycat#1256]
Should the Sentry SDK dependency be moved to core instead of heroku, as otherwise the project will not build (as in the TournamentMixins, configure_scope is imported from the module regardless of settings).

Futheremore, it seems that DISABLE_SENTRY should be set to True by default in the local settings for developments, unless there is a clear use case for having the alternative.

I will look at introducing PRs for these later this week, if these changes sound good with the team.

**Comment by tienne-B** [comment]
The Sentry SDK should stay with the Heroku dependencies, as it is only used on Heroku, and probably not locally or elsewhere. Good catch with `configure_scope`. For that, the module could be set to import only if Sentry is enabled (by moving the import clause to the block that uses it).

Also, I'd agree to setting `DISABLE_SENTRY` as `True` in the development settings. However, it is so when using the local settings, as `DEBUG` is `True`.

I'd look forward for your PR(s)!

**Comment by philipbelesky** [comment]
Agree that some PRs would be great. Nominally we support running local copies of Tabbycat to tab actual tournaments (rather than just for development purposes) but I don't think those need to be instrumented — particularly given the people who are most likely to run locally are also those most likely to want to edit the code and create false alarms. We usually get more than enough reports from web users to surface any common issue quickly.

**Comment by philipbelesky** [comment]
Rather than rely on the `DISABLE_SENTRY` flag I've wrapped the import in a try/catch as that seems more fool-proof than trusting the flag to be set correctly
