### ISSUE TITLE
Where should the API be located

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1343]
With the current work in a Tabbycat API, we should have a standard pattern for the API endpoints. The main decision would be where should the endpoints be located. Should they be:
* In a new app, like notifications
* In their constituent apps

I'd suggest separating the API code to a folder "api" of each app.

**Comment by czlee** [comment]
Great question.

Starting from the URI: I think my first instinct is to have an "/api/" straight after the root—like, before the tournament name, e.g. "https://mytournament.herokuapp.com/api/". It might be "/api/v1/", if we want to do versioning in the URIs.

Of course, this can be done either in a standalone app or constituent apps. It's just a little bit easier in a standalone app, because we wouldn't have to do the urls.py gymnastics we do with the /admin/ URLs. I think the better answer's not that clear to me, but if it's a truly RESTful API, putting the API in its own app wouldn't be illogical if it doesn't have too much shared functionality beyond models.

Unless we think the serializers would actually be shared?

**Comment by tienne-B** [comment]
I don't think serializers would be shared.

Other things to consider:
* The use of keys in APIs, whether to prefer asking for foreign keys or more readable fields (_i.e._ names instead of ids).
  I think names would be preferable so that less information (fewer requests) need to be made to be able to modify elements through the API. It is also easier to write without remembering codes.
* What formats to accept. There is a brief discussion of that in #911, between GraphQL, CSV, and JSON. With Django REST, `GET` requests could return both CSV and JSON with a `&format=` parameter.
  While data could be taken in the form of CSV, creating and updating objects should be in JSON.
* What to do with the makeshift API endpoints. We have basic CSV API endpoints for adjudicator scores and lists of feedback.
  Should deprecate and remove them, and possibly create other ways to access that information, without being beholden to the existing structure. The bulk create text boxes used for updating base scores as well as creating venues and institutions as well (not necessarily with an API endpoint in the admin interface).

Pinging @nickdbush and @jacklishufan as they have expressed interest and work in the development of the API.

**Comment by jacklishufan** [comment]
On choices of keys, I prefer legible strings. However, I do see a problem given the way models are structured right now, as many of the name fields ('reference','name','code', or whatever) which could be used for API are not unique. For instance, neither institution names or codes are unique—they are 'unique together'. In an unlikely scenario where there are two institutions with the same code but different names, using code as the identifier would be clearly problematic. This applies to teams and speakers as well, where it is very likely for different objects to have the same name/reference.

**Comment by czlee** [comment]
Thanks for your interest, everyone!

Most names in models are intentionally not unique. You can't guarantee that two people don't have the same name, so uniqueness there will always rely on primary keys. As a principle we try not to enforce uniqueness at the model level unless technically necessary—as in, it's impractical not to crash without uniqueness, not merely "it's sensible", since there are sometimes things tournaments want to do where the best "hack" is to have two objects with the same name, and I don't want database-level constraints to get in their way.

(I don't know why institution has a name-code unique-together constraint. It probably shouldn't.)

The way to uniquely identify instances is by primary key. If a third-party is developing to use this API, I expect their code to be capable of sending multiple requests. I'm interested in avoiding N+1 problems; I'm not interested in cramming a constant number of requests (independent of tournament size) into one. A human might like being able to remember things by name, but a third-party application knows nothing about the data in a Tabbycat database before it sends its first request, and surely has some notion of memory allowing it to remember objects it needs to reference later (or present them to humans to choose from, if necessary). RESTful APIs normally provide links to the URIs for related objects.

This isn't a novel concept. Most APIs use some sort of meaningless numeric or alphanumeric ID as their primary key.

The exceptions are instances that have slugs for this purpose instead: currently, tournaments and break categories. For those, the API ideally should be able to accept either ID or slug (and should definitely return both).

The makeshift API endpoints should be deprecated then kept around for legacy purposes for one version.

**Comment by jacklishufan** [comment]
I am aware that using primary keys is a common practice to identify objects in a lot of contexts.  I agree that we should not enforce uniqueness on the model level. However, I discovered many attempts to enforce it in the existing models. ("joint uniqueness" of name and code for institutions, also joint uniqueness of institution, tournament, name for teams) These attempts make it possible to identify an institution by name+code and a team by institution+touranment+name. These constraints are there already, so the real question is what to do with them.

**Comment by czlee** [comment]
Yeah, this is a good observation, there are some unique-together constraints that probably shouldn't be there. They'll be hangovers from earlier days, when we had different use case assumptions, or just didn't know better. 🙂

**Comment by prasgema** [comment]
Hi All!
I wanna give my two cents for a RESTful API. Stuff like this usually have best practice you can google, let me help with starters:

**1. Where should it be located**
Yes, i would highly suggest new app. Reason being is that this is a completely different logic from other app. This module never touch or call any functions that tabbycat currently has. Actually there has been a lot of discussions about this you can google. The keyword would be "separating MVC and REST"

If possible, you might want to start working this in a separate code base too. This is because, when you make API, you must've been considered that your app is used by any other app you might have known before. You want to: (a) Keep some logic only accessible to tabbycat; or (b) Separate workload between main tabbycat and client-facing backend app. If you want to consider alternative programming framework specifically designed for RESTful API: [feathers (js)](https://feathersjs.com/) or [flask (python)](https://www.palletsprojects.com/p/flask/)


**2. Naming**
I +1'ed @czlee on the naming. we need to make a `/api/` and their versions `/api/v1/` (or `/api/v1_0_1/` for version 1.0.1). And versioning would be a pain in the ass when the app and consumer base gets bigger. Most of the time, newer version of API is deployed as a new application

More on versioning: https://restfulapi.net/versioning/
More on naming: https://restfulapi.net/resource-naming/
Don't mind the part where they use subdomain instead of subdirectory

**3. Unique Identifier and Keys**
It's a common convention that keys should always be the primary key of each model (or slug). Usually if you want to use a more legible string, you can use a HTML params instead, one that looks like this: `/speakers?name="Prasetyo"` and it should return an array.

In the case where slug is used, common convention requires us to be able to identify as slugs OR id. So the method should be smarter in knowing whether we are accepting string or integer. **P.S:** this would be harder if later we implement mongodb as their IDs are string.

**4. GraphQL**
Actually there are several [articles ](https://www.prisma.io/blog/how-to-wrap-a-rest-api-with-graphql-8bf3fb17547d)about people who wraps RESTful API inside a GraphQL API. However as this is a completely different logic, I think we should not mix up RESTful and GraphQL. Unless if we aim to build GraphQL now. P.S: we can reserve it in `api/v2` or `api/v3`

**5. Downloads**
+1 on @tienne-B for adding `&format=` for download alternatives. But usually this is only applicable to lists only. By default they should always return JSON.

Hope this helps. I'm open if there's anything else you guys want to ask about RESTful API.
I will soon be catching up with #1351 and #1356

**Comment by tienne-B** [comment]
@prasgema, thank you very much for your advice! About point 3, where slugs are used, as we (will) use hyperlinks to objects, and minimal exposure of the ids, why is it important to have the option of getting the object by id as well as slug? Thank you!

**Comment by prasgema** [comment]
Actually, people took extra effort to create legible URL in a site is because they want it to be easily indexed in search engine. It's part of SEO strategy as well.

But in reality, putting slugs (or any string) as key of reference would need extra effort to implement (and maintain) as well as performance drawback. As for DB, integers are easier to index than strings.

So actually it'll make total sense if you use things that people search a lot on google, e.g: tournament, rounds. But not so much for institutions/speakers as it is: (a) longer string; and (b) people never really want to search them by google before getting into our app.

There's second reason for having a legible URL: which is giving a sense of navigability. This is not relevant for API and not relevant to the use of slug.

All in all, those things i mentioned above are not really a thing that developers (which are the users of our API endpoints) wanted. As a software developer, I guess it's much easier if I can simply configure using integers (I also took the liberty to ask 6+ of my colleagues--we all agreed that integer params are easier to manage).

**Comment by philipbelesky** [comment]
@tienne-B not sure if you have seen, but there's also a slug vs ID [consideration over here](https://github.com/TabbycatDebate/tabbycat/issues/1356#issuecomment-570402509)

**Comment by tienne-B** [comment]
The discussion here about location has been resolved with a new app, and the remaining points have shifted to other tasks.
