### ISSUE TITLE
List of API endpoints

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1356]
To have a general idea of the endpoints there should be and the progress being made on them. Feel free to add items and leave comments!
- [x] tournaments
  - [x] _slug_
    - [x] teams
      - [x] _id_
      - [ ] emoji
    - [x] speakers[1]
      - [x] _id_
        - [x] checkin[8]
      - [ ] ~privateurls~
    - [x] adjudicators[3]
      - [x] _id_
         - [x] checkin
         - [ ] feedback[7]
      - [ ] ~privateurls~
    - [x] institutions
      - [x] _id_
    - [x] break-categories
      - [x] _id_
        - [x] eligibility[2]
        - [x] breaking
    - [x] speaker-categories
      - [x] _slug_
        - [x] eligibility
    - [x] venues
      - [x] _id_
      - [x] checkin
    - [x] venue-categories
      - [x] _id_
    - [x] rounds
      - [x] _seq_
        - [ ] availability
           - [ ] checkins
           - [ ] teams
           - [ ] adjudicators
           - [ ] venues
        - [x] debates (draw)
          - [x] _id_
            - [x] ballots[5]
              - [x] _(ballot submission) id_[6]
          - [ ] regenerate
          - [ ] allocate
    - [x] feedback-questions
      - [x] _id_
    - [x] feedback
      - [x] _id_
    - [ ] checkins
      - [ ] generate
    - [x] preferences[4]
    - [x] motions
      - [x] _id_
- [x] institutions
  - [x] _id_

1. I am conflicted on whether to embed speakers within `teams/` as speakers are defined as being members of teams.
2. The `eligibility/` endpoints are separate from their respective detail views as to permit easier updating of participants eligibilities and re-using `PATCH` and `PUT` without worrying for other fields.
3. This endpoint should be able to supersede #911.
4. A preferences API is provided with [dynamic_preferences](https://django-dynamic-preferences.readthedocs.io/en/latest/rest_api.html).
5. Ballots will use `DebateResult` objects but be identified by their ballot submission. A query string could be appended to exclude non-confirmed or discarded ballots.
6. With submissions, the `DELETE` verb should mark the objects as discarded/unconfirmed rather than deleted from the database to keep the version history. As with that, `PUT` and `PATCH` should be disabled to force creation of new objects.
7. As the target adjudicator. `POST`ing will be similar to the `/debate/` feedback endpoint. Could be good to replace #910.
8. Participant checkin would be for that specific participant, while `/checkins` would allow for bulk check in/out, with similar methods to the `/eligibility` endpoints. Participant checkin would however only allow `PUT`, `DELETE`, and `POST`, the latter as a toggle.

I am surely missing some endpoints and I am somewhat unsure of my structure. There are a few ideas with the design. The main point is to not have a singular endpoint to get a resource, like with setting checkins or giving adjudicator feedback. This allows for more efficient queries, avoiding irrelevant results, like for trying to get all feedback for an adjudicator through the `/debates` directory.

I have not included `/create` endpoints for many of these models as the creation should be handled by `POST`ing to the "root" endpoint of the model.

Thoughts and stuff to add?

**Comment by philipbelesky** [comment]
I don't have many thoughts on API design, but thanks for all the planning and implementation thus far. I suspect we may need to wait for actual users to get a sense of how well it works.

**Comment by jacklishufan** [comment]
So you prefer one unfiltered institution endpoint parallel to tournaments under root with no filtered ones under tournaments?

**Comment by czlee** [comment]
Thanks for your work on this so far!

My main comment is to suggest not being wedded to the existing UI structure. The way we think about actions for human users should be quite different to how we think about them for the API. The whole point of the API is give script writers more flexibility/creativity with how their tournament works, so to have the API be an automated version of the UI would defeat the purpose.

This means that as a principle I'd stick much more closely to the actual model structure, just offer straightforward create/update/delete methods, and forget about anything involving intelligence.

In particular, this means I don't think the following should be APIs, at least not yet:
* Anything we label "generate" in the UI (draws, breaking teams, private URLs, check-in identifiers)
* Any auto-allocate function (adjudicators, venues, panels, prioritisation)
* Anything we label as a verb that just changes a Boolean field, _e.g._, "release", "unrelease", "check in", "mark complete" (API users should do this by updating the relevant object)
* Anything relating to an entire ballot submission or entire scoresheet

This also means that I think most validation for user protection shouldn't apply to the API. For example:
* The API should not check ballot math (at all)
* The API should not check that there is exactly one debate-team in every position of a debate
* The `DELETE` method on a ballot submission should actually delete it from the database, and `PUT` and `PATCH` should work as normal
* Own-institution conflicts should be not automatically added

Paraphrased: I think of the API as an automated version of the Edit Database area, not the Tabbycat UI.

We can rethink this principle as necessary to reflect what we learn about actual user needs, but I think this principle is where we should start.

An argument against this approach is that it locks us too tightly to the model structure, as in, ideally we'd want to be able to rearrange the database schema without breaking the API. I don't have firm views on this yet, other than to say that I'd be willing to consider relaxing the above principle where appropriate. Scoresheets come to mind for this. But even here, the API should still _look_ like a representational state transfer, it just might not strictly match the database schema.

But that discussion can come later. I still think there's plenty of low-hanging fruit that's best achieved by only implementing REST-style low-level create/update/delete methods directly related to objects, most notably registration data import (which should include `DELETE` functions, so that intelligent reg systems can run some sort of "sync") and adjudicator feedback processing.

**Comment by tienne-B** [comment]
@jacklishufan: "I am surely missing some endpoints" would apply here ;)

@czlee: I agree that the API shouldn't be beholden to the structure we use for the UI. I don't think I've fallen into that trap though; I was just putting endpoints where they seemed to make sense, sometimes at several places, in order to be flexible. The structure is meant to be the least restrictive; I'd find it a good sign that it somewhat mirrors the UI structure in that it shows good reusable structure.

I disagree however in forgoing "intelligence." If someone just wants the database structure, they might as well just use raw SQL. The API should be able to perform actions that the UI can do easily, just that it isn't bound to use those methods. Not giving access to perform our algorithms would make the API less performant and expressive.

As for some of the specific cases:
* **Participant details generation** (private URLs, emoji, checkin-ids): There is not much in the generation of these fields, and I don't think API clients should be required to handle them if needed for the tournament. These functions serve to offload some responsibility for which the the client might not care about at the time of using the "main" endpoint.
* **Auto-allocation**: The API should be able to perform all actions done in the UI. Auto-allocations may be useful to API clients if they want to use Tabbycat's algorithms. This use-case should not be prevented.
* **Booleans**: True. I've just removed some. However, I wouldn't include checkins as it is separate from the "subject" object in the model and in use, different from the subject itself.

As for ballots, building upon #1180 for submissions would relax the requirements and not obligate correct ballot math. I think of having `DebateResult` as a very important abstraction to combine all the score tables into a cohesive ballot, which should be our object with the endpoint(s), not needing to expose further. I don't think there should be endpoints for `TeamScore` and others in favour of `DebateResult` and its result handling. This also goes with being able to re-arrange models without affecting the API.

Agree that most validation should not apply, and that there is quite a bit of "low-hanging fruit" that could be done before worrying about more, with a wide vocabulary of HTTP verbs.

A concern I have is how should we deal with logging and record-keeping with the API. We have the `django_admin_log` for the DB interface and `actionlog` for the UI. Taking it that we'd want to log the use of the API, should we try to integrate it in the action log, either with new actions or finding correspondance with UI actions, or some other logging mechanism? I would be in favour of finding UI equivalent actions to have more detail on the action taken, but mark it as API (new field?). This would be more involved though in finding the proper codes (_i.e._ modifying different fields in a model may be associated with different actions). For record-keeping, the API should have a similar mechanism to the UI, not allowing the deletion of certain records (ballots), rather displacing older versions and using the newest. This is something to be firm about, so should only be deletable by the DB interface, rather than Tabbycat itself allowing for it.

Of course we'll re-evaluate when we know more about the use of the API.

**Comment by czlee** [comment]
On reflection, my thoughts perhaps needed further refinement. It might be worth taking a step back and discussing the use-case of the API. Specifics we of course don't yet know, but at a high level:

Rather than "flexibility", what I should've said was, I think the point of an API is to enable third parties to augment Tabbycat with _specific_ functionality that you can't normally do.

So I don't envision someone writing another UI to do everything Tabbycat does, plus more (and I doubt you do either). Rather, I imagine there are specific things, like:
* a registration system that needs to sync with Tabbycat
* more elaborate adjudicator feedback options than what we're willing to build
* scripts to update adjudicator scores using an adj-core-designed formula
* scripts with a more complicated adj-core-designed adjudicator allocation algorithm
* tournaments with special draw pairing rules (like educational development leagues)
(none of these examples are hypothetical)

Perhaps one day someone will want to write some augmenting functionality that relies on being able to automatically trigger Tabbycat's own draw generation or adjudicator allocation algorithm, and if someone asks for it, I'll reconsider. But to me, the "intelligent" functions are things that _users do_, not likely components of functionality that someone wants to _add_. In terms of scope I think of them like plug-ins, except that they live outside Tabbycat.

(Quick aside on ballots: since scoresheets _are_ a data structure, I'm actually open to building the API in these terms, because the interface can still be a "representational state", provided it's not validated.)

For now, putting all that aside, I'd like to focus on things that will definitely be used by the most pressing API needs, and roll out with a minimum viable product (when it's ready, no rush). It's tempting to brainstorm other endpoints, but even very simple redundant ones add code that needs to be maintained. Maybe we could refocus our progress list there? I think the two most common requests are registration import (like #1329), and external adjudicator score updates (what feedback.csv and scores.csv are used for).

For registration:

- /institutions/[ID/]
- /tournaments/SLUG/teams/[ID/]
- /tournaments/SLUG/adjudicators/[ID/]
- /tournaments/SLUG/
- /tournaments/SLUG/break-categories/[SLUG/]

**Comment by czlee** [comment]
On reflection, my thoughts perhaps needed further refinement. It might be worth taking a step back and discussing the use-case of the API. Specifics we of course don't yet know, but at a high level:

Rather than "flexibility", what I should've said was, I think the point of an API is to enable third parties to augment Tabbycat with _specific_ functionality that you can't normally do. So I don't envision someone writing another UI to do everything Tabbycat does, plus more (and I doubt you do either). Rather, I imagine there are specific things, like (none of these examples are hypothetical):
* a registration system that needs to sync with Tabbycat
* more elaborate adjudicator feedback options than what we're willing to build
* scripts to update adjudicator scores using an adj-core-designed formula
* scripts with a more complicated adj-core-designed adjudicator allocation algorithm
* tournaments with special draw pairing rules (like educational development leagues)

Perhaps one day someone will want to write some augmenting functionality that relies on being able to automatically trigger Tabbycat's own draw generation or adjudicator allocation algorithm, and if someone asks for it, I'll reconsider. But to me, the "intelligent" functions are things that _users do_, not likely components of functionality that someone wants to _add_. I guess I think of them like plug-ins, except that they live outside Tabbycat.

(Quick aside on ballots: since scoresheets _are_ a data structure, I'm actually open to building the API in these terms, because the interface can still be a "representational state", provided it's not validated.)

For now, putting all that aside, I'd like to focus on things that will definitely be used by the most pressing API needs, and roll out with a minimum viable product (when it's ready, no rush). Maybe we could refocus our progress list there? I think the two most common requests are registration import (like #1329), and external adjudicator score updates (what feedback.csv and scores.csv are used for).

(In these lists, [ID/] means "list/create view without ID, detail/update/delete view with ID")

For registration:
- /institutions/[ID/]
- /tournaments/SLUG/rounds/[SEQ/]
- /tournaments/SLUG/teams/[ID/]
- /tournaments/SLUG/adjudicators/[ID/]
- /tournaments/SLUG/speakers/[ID/] _(note 1)_
- /tournaments/SLUG/break-categories/[SLUG/]
- /tournaments/SLUG/speaker-categories/[SLUG/]
- /tournaments/SLUG/venues/[ID/]
- /tournaments/SLUG/venue-categories/[ID/]
- /adjudicator-team-conflicts/[ID/] _(note 2)_
- /adjudicator-adjudicator-conflicts/[ID/] _(note 2)_
- /adjudicator-institution-conflicts/[ID/] _(note 2)_
- /team-institution-conflicts/[ID/] _(note 2)_

_Notes:_
1. _On @tienne-B's footnote: I feel like it's simpler to have speakers not under teams, and to have the team detail view list speakers and URLs to speaker detail views_
2. _Tournament isn't a field of the conflict models, so probs not much point in /tournaments/SLUG before these?_

For external adjudicator score updates:
- /tournaments/SLUG/adjudicators/ID/  _(update/retrieve scores using this)_
- /tournaments/SLUG/adjudicator-feedback-question/[REFERENCE/]
- /tournaments/SLUG/adjudicator-feedback/[ID/]  _(filter by adj only if requested via query string)_

I suggest that we discuss then implement this list (like with the first list, feel free to suggest additions/removals/changes), then roll it out for client writers to try out and get feedback on these use cases first. There'll probably be something practical that we only discover when people try it out for the first time, and it'll save us a lot of refactoring to discover it while our implementation is still small.

**Comment by tienne-B** [comment]
Oh yes, I agree with your prioritization. I didn't make my priorities clear. Also, I get your idea with "intelligent" functions.

On conflicts not having a tournament field, this is somewhat the discussion with institutions. I'm flexible on this and uncertain, but I think I prefer having it in `/tournaments` to have it on the same level as the participants, and in the fact they are not cross-tournament as with institutions. If we decide to place "top-level," the API should be filtrable (URL query argument) by tournament.

With URL query arguments, I'm turning around to your feedback endpoint, for which should be filtrable at least by target _or_ round.

**Comment by prasgema** [comment]
After understanding the use case, we might want to identify the integration points too. For example:
A feedback application might need to access `GET /tournament/SLUG/round/seq/debate/` but not `POST /tournament/SLUG/round/SEQ/debate/` or `PUT /tournament/SLUG/round/SEQ/debate/ID` 

I'm giving you an example of possible integration with a feedback application:
* `GET /tournament/SLUG/round/SEQ/debates/`
* `GET /tournament/SLUG/speakers/`
* `GET /tournament/SLUG/adjudicators/`
* `GET /tournament/SLUG/teams/`
* `GET /tournament/SLUG/institutions/`
* `GET /tournament/SLUG/venues/`
* `GET /tournament/SLUG/feedback-questions/`
* `POST /tournament/SLUG/round/SEQ/debates/ID/feedback`

Sometimes we might not need to prioritize certain operation because: (a) no one will use it; or (b) we should never let third party app delete existing feedback.

Another note, we might want to consider usage of [OAuth ](https://oauth.net/2/) to get the third party app authenticated. Fastest and Easiest alternative would be forcing third party app to embed username-password pair inside their request header.

P.S: this is not that important, but people usually use `:id` for key. So it usually looks like this `tournament/:slug/round/:seq`

**Comment by philipbelesky** [comment]
I haven't been super-closely following this discussion (sorry!) but one question I had was regarding the choice of slugs vs IDs in paths. I think it makes sense to have tournaments accessed by path, but for other types of data (e.g. break categories) wouldn't ID be a safer and more intuitive choice? Slugs change more often than primary keys, and may lead to API consumers making inadvertent choices (like the primary break being called 'open'). 

This may be somewhat moot, as I suspect that any consumer app would ask for the site url, tournament slug, and credentials before autodiscovering the relevant data it needs (whether by ID or slug). But, at that point, using ID/primary key seems the safer choice.

**Comment by czlee** [comment]
Yeah, this is a fair comment, actually. See also discussion starting at https://github.com/TabbycatDebate/tabbycat/issues/1343#issuecomment-570273185.

**Comment by prasgema** [comment]
Yep. I agreed. Actually I also commented on this issue [here](https://github.com/TabbycatDebate/tabbycat/issues/1343#issuecomment-570525209) 

To make it clearer to you guys. This is how my code will look like when I want pull tabbycat data:
```
url = 'https://tabbycat.com/tournament/:slug/round/:seq/debates/'
slug = 'MDO2018'
seq = 3

http.get(url, {slug, seq}, function(res){
  // do logic here
})
```
**Nodejs**

**Comment by tienne-B** [comment]
This will not be RESTful, but there should be an endpoint to `POST`/`DELETE` an `Event` based on a barcode and nothing else.
