### ISSUE TITLE
Adjudicator e-ballot submission

### ISSUE THREAD

**Issue by cm319** [TabbycatDebate/tabbycat#1398]
Hello,
When the setting that makes it so each room only submits one ballot through the chair instead of each judge doing so individually is on, shouldn't this also be reflected on the personal link page? I've found that adjudicators on the panel also have the option to submit the ballot, even though they do not have one.
Thanks.

**Comment by tienne-B** [comment]
Panellists being able to submit ballots is intended, so that in the case where the chair cannot submit a ballot themselves, a panellist can do so instead.

You should also note that in voting formats, where all adjudicators have a ballot, all ballots must be submitted at once, so it would be one adjudicator that submits all of them. Letting them be submitted individually is tracked on #254.

**Comment by cm319** [comment]
Thanks for the quick response.

Regarding private URLs, is there a way to only generate them for/only print or email out the ones for the Adjudicators? Mass generation also generates them for speakers as well, and that can be a nuisance.

**Comment by tienne-B** [comment]
While it is not possible to automatically generate private URLs for just one class of participant (speaker/adjudicator), other than manually or using the `dj privateurls` command (with the `--adjs-only` option). Using the Heroku command line is somewhat advanced and creating private URLs for everyone does not require any extra work really and they would still appear in the list even if the URLs are not used or are inexistant.

For emails, you are able to click a few buttons to exclude/include these classes:
![Private urls](https://user-images.githubusercontent.com/6293465/73774583-3a58a600-4752-11ea-8ff2-8dcfff691ce8.png)

However, it is not possible with printing. I suggest opening a new bug to discuss ;)
