### ISSUE TITLE
Question - Running many outrounds concurrently

### ISSUE THREAD

**Issue by cm319** [TabbycatDebate/tabbycat#1400]
Hello,
Is it possible to run many finals at the same time? (i.e. Grand Final and ESL Final) Only one of them has the blue icon in tabbycat at a time and I am not sure whether assistants will be able to display the draw because of that limitation.

**Comment by czlee** [comment]
Should be! We introduced this LaPerm (2.3), which we released in September. Once you get to the outrounds, the first outround in each break category that is not complete should be appear to be "current", and assistants should have a view of the draw that permits them to show all current rounds on the same page. Let me know if you're having trouble getting that working?

**Comment by cm319** [comment]
What I'm trying to create is a system with 3 different finals: One for the teams that ranked 1-4, one for the teams that ranked 5-8, and one for the teams that ranked 9-12. How could I integrate this into Tabbycat?
Thanks

**Comment by czlee** [comment]
For that you'll need to set something up manually. Here are two ideas:

Simpler way: Create a single round call the "finals", make its draw type "manual", and allocate teams by drag-and-drop (under "edit matchups"). Then run the round as a normal round. Which debate is the 1-4 won't be marked on the draw, but it'll be obvious if you have current team standings public.

Complicated way: Create three break categories, called "1-4", "5-8" and "9-12", and create a single elimination round in each of them. Then allocate teams by drag-and-drop to each one. Now it'll look similar to open/ESL/EFL finals in the draw.

Unless it's really important to mark which final is which in large bold text, I'd recommend the simpler way, because it has a lot less clicking through pages just to change one debate.

**Comment by cm319** [comment]
Thanks for the quick response! 
I've already made what you described in the second method.I just got a bit confused while testing it on a local installation due to being able to mark i.e. adjudicators available for multiple outrounds at the same time.

**Comment by czlee** [comment]
Normally the way people do this is to set the breaking adjudicators (under feedback), then use the "mark all breaking adjudicators as available" button in each break category individually. But if you want to allocate judges for all three rounds in the same allocation screen, this isn't currently natively supported. One hack is to change the round of each debate in the Edit Database area to one of the rounds (doesn't matter which) so it looks like they're in the same round, allocate adjudicators from that round, then change the round of each debate back. We did this at WUDC, but personally I think this is way too much work for your case, so if I were you I'd just use the simpler way 🙂

**Comment by cm319** [comment]
Roger. Thanks very much!
