### ISSUE TITLE
Postings output to API

### ISSUE THREAD

**Issue by SJinAK** [TabbycatDebate/tabbycat#1436]
Hi there,

I'm working (in a non-technical capacity) with Yaatly.com and am hoping that we can ask for postings to be output in a CSV file.  With such a file from TabbyCat, we can directly upload the posting to Yaatly and automatically create rooms for an online tournament (complete with team names and positions as well as judge names).

Any chance this is simple to do?

**Comment by tienne-B** [comment]
Hello! What you're asking would be quite easy. A current project is creating an API so that external applications can get information directly from Tabbycat. The added benefit of that is there should be no need for tab directors to export a file to re-upload it somewhere else; Yaatly could handle the API itself! This will be available in the next version of Tabbycat.

The API endpoint (REST-based) for postings (we call them pairings) is under `/tournaments/<slug>/rounds/<seq>/pairings/`. The little hiccup is that it does not provide team names nor adjudicator (judge) names. Rather, it gives IDs and they can be used to associate them by name (with the `tournaments/<slug>/teams/` and `tournaments/<slug>/adjudicators/` endpoints. You can try the feature branch https://github.com/TabbycatDebate/tabbycat/tree/feature/api to get an idea of how it looks.

This doesn't precisely address creating CSV files (although they could be created based on API output), but I hope the API addresses your use-case. A "dirtier" alternative would be to copy the Vue table content (which is JSON), then filter and convert to CSV. Hope this helps! Feel free to reply if you need anything!

**Comment by skwny** [comment]
hi @tienne-B, Yaatly dev here. Just to clarify, are you saying the API is still under development? Any idea how far out it is? Also, is the Vue table content already available?

Thanks!

**Comment by tienne-B** [comment]
Yes, the API is still under development, but the endpoints you'd need from this task are complete. You may try the feature branch to get a sense of them. There is no timeframe for the release of the next version, which will include the API. The content of the Vue tables is available in the current version and can be scrapped.

**Comment by tienne-B** [comment]
Of course, it'd be best to be able to use the API, but as a stop-gap until the release:

For the structure of the Vue table content, the JSON for the debates can be obtained with `vueData.tablesData[0].data` on the JS console for draw pages. Each element of that array is itself an array, the first element's `text` being the room name, the subsequent elements (ordered by position) being the team names, then the last being a concatenated list of the judges for the room.

**Comment by tienne-B** [comment]
Pairings will be listed as debates, in this format: https://app.swaggerhub.com/apis-docs/tienne-B/Tabbycat/1.0.0#/Debate (with the GET endpoint `/v1/tournaments/{tournament_slug}/rounds/{round_seq}/pairings`)

**Comment by skwny** [comment]
@tienne-B thanks. The API is not live yet, correct?

**Comment by tienne-B** [comment]
Finishing touches for the next release; will be available on instances using Tabbycat v2.4
