### ISSUE TITLE
HTML entities should be allowed in popovers

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1691]
For i18n, French ordinals use superscripts, but the HTML entities appear in popovers in result and standings tables.

**Comment by czlee** [comment]
We probably need to apply `mark_safe` somewhere, right? Normally we only do that when we know we need it. The key really important thing is that any text with `mark_safe` applied to it must have absolutely no user-specified text in it, or at least no text from users we don't trust (i.e., the tab director). So this should be fine. (Translations are too, obviously.)

Can we single out those particular strings (in the English source) where it appears to be marked as safe, rather than apply a blanket to everything in a popover? Django's `mark_safe` system is pretty smart about things like this. Or is this issue more widespread than just ordinals?

(Also, just wondering, what happens if we insert Unicode characters into the translations?)

**Comment by tienne-B** [comment]
I don't think `mark_safe` would work (might be wrong though), as this bug is in Vue tables, and all the table content is marked as safe in `base_vue_table.html`.

All characters used are in Unicode and encoded in UTF-8 ;) There's no problem with specific characters provided the users have proper fonts to render them.

**Comment by czlee** [comment]
Oh, interesting, okay. Thanks for clarifying!
