### ISSUE TITLE
Teams and adjudicator names selectables in tables

### ISSUE THREAD

**Issue by perplesso82** [TabbycatDebate/tabbycat#1739]
Can you please consider to make adjudicator and team names selectables in table. It could be very useful to copy-paste draw and scores.
Example: List speaker standings, select all the data in table. The position, name and scores will be selected, but team name remains unselected.
![export](https://user-images.githubusercontent.com/78228926/108765377-fa7a8180-7553-11eb-8eae-eb79e67cee8a.png)

**Comment by philipbelesky** [comment]
Hi, thanks for this report? Have you tried to copy-paste from the table you have selected?

In Chromium-based browsers the names do not visually show as selected, but should be present upon copy/paste.

Note for the future: fixing this (to show a visual selection) involves removing/reworking the use of vue-touch and popperjs and the lack of `user-select` is to enable tap-actions (in place of hovers for touch devices).

**Comment by thbsp** [comment]
Actually, the team names don't actually appear when pasting the data. The same issue holds for adjudicator names in the round results table as well. (Tested on Windows 10, using Brave and Chrome (Chromium version 91.0.4472.124).)
I would like to second this request. Having copy/pastable table data would be very useful when creating certificates, break announcement slides, etc. In my last tournament I had to manually type out all of the team names manually since I couldn't find a single place in the interface with standings or round results where the team names could be copied.

**Comment by philipbelesky** [comment]
Thanks for the report @thbsp. There's probably a browser bug or regression somewhere that explains the lack of team name copying, but I think its worth prototyping a dedicated copy button that would be built-in to each table. My first thought would be to place the table on the clipboard (csv formatted) would be better than creating/downloading a file, would you agree?

PS: I'm not sure if you have a background in web dev, but let me know if you were interested in adding this as a pull request and I can help identify the relevant code.

**Comment by thbsp** [comment]
@philipbelesky: For an individual table, I agree that copying to the clipboard would be better than downloading a file.
(That said, I created a separate issue to suggest a more robust data export function, and there I think there downloading a file or set of files would be more practical.)

PS: Thanks for the offer. I know enough about coding to read through simple code and see what it does, but not really enough to write proper code of my own.

**Comment by philipbelesky** [comment]
Thanks for the feedback. I've added in a button - it should be in the next major release.
