### ISSUE TITLE
Add .CSV export utility for team standings, speaker standings, adjudicator standings, etc.

### ISSUE THREAD

**Issue by thbsp** [TabbycatDebate/tabbycat#1837]
Currently it's rather hard to get Tabbycat tournament data out of Tabbycat.
An option to export to export the tab data as a .CSV or another format would be very useful for:
* creating certificates for debaters / adjudicators
* creating break announcement / closing ceremony slides
* analyzing tournament data in spreadsheet / statistical programs
* reporting data to overbearing bosses
* backing up tournament data (just data, not the entire Tabbycat installation)

Edit: I realized I should be more specific. My suggestion would be to add an **export tournament data** page to the configuration page. The page could have a series of checkboxes for each set of data that someone might want:
* Round results
* Team tab
* Speaker tab
* Judge tab
* (others?)
An export button would then download a .zip file with each checked item as a .csv.

**Comment by tienne-B** [comment]
This is a _won't fix_ for me. Standings are accessible through the API, which is a JSON format so is much more flexible, but you can convert to CSV. Our full API reference is at `api-schema.yml` or https://app.swaggerhub.com/apis-docs/tienne-B/tabbycat-api/v1.1.0 , with standings like https://app.swaggerhub.com/apis-docs/tienne-B/tabbycat-api/v1.1.0#/v1/v1_tournaments_teams_standings_list

We are also working on an export format for tournament data as DebateXML, which will be available in the next version.

**Comment by thbsp** [comment]
I wasn't aware of the API. Having any type of export function would be great.
I would mention though that having an option that's reasonably accessible to people without extensive technical knowledge would be great. I can think of a lot of people that may want to run a tournament and do something with the data afterward, but saying "you can export through an API" would mean nothing to them.

**Comment by tienne-B** [comment]
I would suggest the DebateXML export for all data after a tournament, but that'd still be more technically-inclined. If what people want is just a textual format of what is already displayed in tables, #1739 would be the best in user-friendliness and maintainability.

I also want to limit the amount of content in the main codebase. What's being asked seems more like a utility which could be spun off to some online tool, avoiding clutter, by using the API.

**Comment by czlee** [comment]
For what it's worth: I share the concern about code clutter and mission creep, to see why a CSV feature might run into this perhaps requires some elaboration. I think CSV exports raise a bunch of structural questions about what the CSV files look like. Debate tournament data is highly cross-referenced, and I don't see any obvious ways to represent it faithfully in a two-dimensional table. For example, the speaker tab and team tab drop information about opponents and speaker positions. You could reconstruct this from the draw, but you'd need to be sure team and speaker names are unique—and what about institutional affiliations? For the sorts of analyses I imagine people want to do, you probably want to be able to collate this data into tables in different ways, depending on what you're trying to analyse.

At least, that was my thinking when @philipbelesky and I first proposed the DebateXML idea back in 2015, which @tienne-B later brought to fruition.

So to the extent that I imagine a third-party utility, it's not so much because CSV files _themselves_ require them, so much as it is that I think a good, robust CSV tool probably requires user input to specify how those CSV files look, which can probably get a little bit complicated. The clutter, I'd suggest, comes from this.

Of course, one might object that I'm letting the perfect be the enemy of good, to which I wouldn't disagree… but hopefully this gives some insight into why friendlier exports aren't necessarily a high priority, relative to getting the API and XML export underway. Hopefully these latter two ideas (with thanks to @tienne-B, who is basically doing all of it!) will allow a broader community (initially, those with the requisite technical background) to build on it, including some who might be able to produce tools to convert to other formats as necessary, or maybe even to (e.g.) automatically generate certificates/slides directly from the API. But I know that's not much comfort for the short term.

Also, while I'm here—thanks for reporting all the other issues too, @thbsp!
