### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by MELCHI-TABBER1** [TabbycatDebate/tabbycat#1845]
I hit an internal server error while trying to load this URL:
https://gyabaahtabz.herokuapp.com/uccinterhalls21/admin/draw/round/5/

Please describe what you were doing when the error happened, along with any other useful information:

**Comment by tienne-B** [comment]
Thanks for bringing it to our attention. I have commented on your FB post yesterday on the same topic: https://www.facebook.com/groups/tabbycat.debate/posts/1920249598142988/, and I hope that answers your problem. However, this problem has been fixed in newer versions, and we don't really support 2.2.10 anymore.
