### ISSUE TITLE
Supervisor Account 

### ISSUE THREAD

**Issue by Zorral** [TabbycatDebate/tabbycat#2184]
When creating a supervisor account for one of my team members, the username and password I set up doesn't seem to work. The email I linked also doesn't receive the reset password link. What could be the issue here?

**Comment by tienne-B** [comment]
Did you make sure they were typing the same thing? Different keyboard, caps lock, etc. As for the reset password link, make sure your email provider is working; you can test with the "Send Test Email" button on the main page. You're also able to reset passwords manually through Edit Database: click on their username and there'll be a link to change their password.

Manually creating accounts is obsolete in favour of setting an account creation key in the "Global Settings" section of the configuration, and giving your team that link so that they may create their own accounts.

**Comment by Zorral** [comment]
Hi! 

Yeah, I did make sure, I changed the username and password multiple times just to check! And the email is most definitely working, we tried 3 separate emails.

**Comment by Zorral** [comment]
I'm not so sure the email is even linked, given that we tried having team members making their own accounts and linking their emails from there, and checked by trying to reset those passwords; we received those links immediately. Could we be making a mistake somewhere else in the setup?

**Comment by tienne-B** [comment]
What's the URL to your site?

Also, make sure the user has a valid email.

**Comment by Zorral** [comment]
Could you give me an hour or so to get home, I will check from there! Thank you so much though in the meantime.

**Comment by Zorral** [comment]
Hi again, so sorry for the delay. I am not so sure what you mean by site link, but I did hand my account to one of my team members, and they are unable to log in even with those creds.

**Comment by Zorral** [comment]
Could you elaborate on what the team link is? I remember setting up a code but my team couldn't find a place to use that code

**Comment by tienne-B** [comment]
What is the URL to your Tabbycat instance?

**Comment by Zorral** [comment]
https://isct.calicotab.com/isct/

**Comment by Zorral** [comment]
I figured it out! Thanks for the help!
