### ISSUE TITLE
Codebase is overreliant on dictionaries.

### ISSUE THREAD

**Issue by daankoning** [TabbycatDebate/tabbycat#2202]
#2201 brought this to light, a lot of functions return complex and compound dictionaries. These are hard to maintain and debug.

In order to reduce the technical debt caused by these I see three solutions:

* In the short term replacing some of them for `TypedDicts` could alleviate this problem a bit. 
* The above is also already quite a significant workload. Instead of the really ugly current typehints perhaps binding some of the compound types to variables could be a bandaid. For example, binding `email = Tuple[Dict[str, str], 'Person']` would change the hints on [email generators](https://github.com/TabbycatDebate/tabbycat/pull/2201/commits/8273fa3041fef97358039b33299cf965dbf03333#diff-e0ae2cf18b7c292b1fb1110dbb487e70533f54e8a82838cd2e4bd4faa1b5350bR87) from `List[Tuple[Dict[str, str], 'Person']]` to the significantly more legible `List[email]`.
* In the long term they should probably be refactored into dataclasses (also mentioned in [this](https://github.com/TabbycatDebate/tabbycat/pull/2201/files/8273fa3041fef97358039b33299cf965dbf03333#r1051492295) comment).

**Comment by tienne-B** [comment]
If we're only talking about email generators, I think the fix is really straightforward and can be in your existing #2201 PR. I don't think the problem you're raising is endemic to the whole codebase, and there is a good reason I only used `dict` for the generators. The generators' data structures are only created in those functions, and their goal is to be used as Django template context, which uses `dict`s.

For these email context generators, this is how they'd be fixed:

https://github.com/TabbycatDebate/tabbycat/blob/62f8caa988a82bf7ca60d7781993e97d8f7a0681/tabbycat/notifications/consumers.py#L87
```py
from dataclasses import asdict
...
    context = Context(asdict(instance))
```

Then, in `notifications/utils.py`:
```py
from dataclasses import dataclass

@dataclass
class EmailContextData:
    USER: str

@dataclass
class AdjudicatorAssignmentContext(EmailContextData):
    ROUND: str
    VENUE: str
    PANEL: str
    DRAW: str
    POSITION: str
    URL: str

...
```
and create them in the generators.

**Comment by daankoning** [comment]
Oh I must've misunderstood your comment; I thought you were refering to the codebase in general, my bad :(
