### ISSUE TITLE
some doubts regarding a few things

### ISSUE THREAD

**Issue by prithwiraj10** [TabbycatDebate/tabbycat#2300]
Hello, 
i want to delete a tabbycat site i deployed through git cmd, how can i do it?
How many sites can i run for free from the github student education credits in a year?
How many tournamets can each site handle?

**Comment by tienne-B** [comment]
1. I'm supposing that you've used the `deploy_heroku.py` script, so you can delete your site on https://dashboard.heroku.com .
2. There is no limit to the number of sites, provided that you remove old ones as to not consume your credits. Check https://www.heroku.com/github-students for details.
3. Unlimited

Please use our Facebook group ( https://www.facebook.com/groups/tabbycat.debate ) rather than GitHub Issues (here) if you have more questions. We use GitHub for software development and Facebook for community outreach.
