### ISSUE TITLE
Help With Local Hosting with LAN...

### ISSUE THREAD

**Issue by ActualAyan** [TabbycatDebate/tabbycat#2346]
The rough guide on documentation page says-

> You need to pass in your computer’s IP address and port to the runserver command, for example, if your computer (the one acting as a server) is 196.168.0.2 and you want to run it on port 8000: dj runserver 192.168.0.2:8000

Now where will I find the **dj runserver** command? or where do I need to implement it? I'm using Docker app for local installation.

**Comment by tienne-B** [comment]
Couple lines above:
> We don't provide detailed instructions for this; we leave it for advanced users to set up themselves.

I don't think we should give instructions more detailed than what we already have, which is what this issue is asking. We expect a certain level of self-sufficiency if deploying by oneself rather than a managed host. You should be able to recognize that the site runs through Docker, and so the step to pass to is how to port forward / open the firewall to access.
