### ISSUE TITLE
Create precedence preference for pullup restrictions

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#2446]
The [WSDC Power Pairing Procedures](https://www.wsdcdebating.org/_files/ugd/669183_acd9f3bd3ab3482ebead22ae0da74fa7.pdf) has a couple different restrictions on pullups:
* **3.5**: Take team from immediately lower bracket
* **3.6**: Avoid teams getting pulled up more than once
* **3.7**: Immediately lower bracket + lowest draw strength by rank (#2445)

It would be good to have some clarity on how these restrictions interact with each-other, as they are quite deferential to each other with "If possible," or general exceptions for other points. In my estimation, if many teams have the lowest number of pullups, the deciding factor goes to **3.7**.

**Comment by SerbiaWSDCCAs** [comment]
So while ideally you want to adhere to all the rules, in scenarios where not all rules can be followed simultaneously due to conflicts, the prioritization is as follows:

1. **Rule 3.10/3.11 (3-5 prop/opp split)** must always be followed, no matter the circumstances. This rule is paramount and overrides all other rules.

2. If a conflict arises where not all rules can be adhered to, **Rule 3.7** is the first rule that can be set aside. While important, it holds the lowest priority in cases of conflict.

3. The next rule that can be compromised, if necessary, is **Rule 3.10/3.11 (4-4 prop/opp split)**. This rule is secondary to Rule 3.10/3.11 (3-5 prop/opp split) and can be disregarded if conflicts arise with higher-priority rules.

4. Following that, **Rule 3.6** can be set aside if adhering to it causes conflicts with the essential rules mentioned above.

5. Lastly, if conflicts persist and not all rules can be simultaneously followed, **Rule 3.5** can be the next to be compromised. This rule, while significant, is the highest in the hierarchy of rules that can be set aside when conflicts with other critical rules occur.

Thus if conflicts necessitate not following some rules, the order of compromise should be: first Rule 3.7, then Rule 3.10/3.11 (4-4 prop/opp split), followed by Rule 3.6, and finally Rule 3.5.

**Comment by SerbiaWSDCCAs** [comment]
REVISED COMMENT:

**Comment by tienne-B** [comment]
Superseded by #2513
