### ISSUE TITLE
Create option to show percentage of unsubmitted feedback by source

### ISSUE THREAD

**Issue by gizapavone** [TabbycatDebate/tabbycat#2494]
To check for adjcore rules for breaking a judge based on submitted feedback, it would be useful to see the percentage of submitted or unsubmitted feedback per judge. Additionally, being able to sort this on Tabbycat based on this filter would be helpful. Since the expected amount of feedback from each judge varies depending on the size of the panel (at least for chairs), this feature would make it easier to check adjcore rules without the need for a script.

**Comment by tienne-B** [comment]
Would this be to add a column to the "Feedback Overview" page? Also, I don't know of AdjCores having a percentage cut-off (rather than just a maximum number of unsubmitted feedback); mind providing an example?

**Comment by tienne-B** [comment]
The rule for which this issue was raised is more complicated than "percentage of expected feedback submitted," rather it is "percentage of active rounds with all expected feedback submitted," which is more complicated and more specific to a particular tournament.

I don't think this would be of much help in general, and tournaments with more complicated rules can use the API to calculate/update.
