### ISSUE TITLE
Consider pre-setting a debate's importance given a room's liveness

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#332]
It would probably save a decent amount of time at large tournaments, and not be too much of an overreach if debates defaulted to 'smart' importance values rather than 0/neutral. I would suggest at the point dead rooms are knowable their importance would be set to the lowest possible (-2) whereas rooms with one live team be set to +1 and two live teams to +2. 

I could also see the argument for 'live' rooms to be set to just +1 regardless of the number of live teams in order to preserve the +2 as a manual override/tweak. 

Depends on #323

**Comment by philipbelesky** [comment]
Hasn't made it in for Australs, but probably still worth exploring. Removing the milestone so it can be reconsidered for a future release.

**Comment by philipbelesky** [comment]
I'd be keen to add this to Melbourne Mini as a testing ground. 2 quick questions:

- Should this be a step that happens at draw generation?
- Or should it be an explicit step as part of the automation allocation process in the edit adjudicators interface? In the later case it could prevent having to recalculate the Break thresholds

How does this sound as a rough formula:

- Debates are grouped into thirds based on their brackets; which maps to a -1 to + 1 range. IE 41= top 33% of debates; -1 = bottom 33% of debates
- For 2vs2 each team that is live for for each category adds 0.5 points of importance. For BP the same rules applies but at +0.25
- For 2vs2, each teams that is 'dead' or for each break category within the debate subtracts 0.5 points of importance. For BP the same rule applies but at -0.25.
- Scores below -2 or below 2 are floored to those ranges

Scenarios:

- Top 33% debate, all teams live. +2
- Middle 33% debate, all teams live. +1
- Bottom 33% debate, all teams live. +0

- Top 33% debate, all teams safe. +0
- Top 33% debate, half teams live, half teams safe. +1.5
- Middle 33% debate, half teams live, half teams safe. +0.5
- Middle 33% debate, half teams live, half teams dead. +0
- Bottom 33% debate, all teams dead. Equates to a -2

- Middle 33% debate, half teams live in 1 category, half teams live in 2 categories. +1.5
- Middle 33% debate, half teams dead, half teams live in 1 category. +0.5

I'm not sure the handling of liveness works amazingly well at promoting importances, although at the point it becomes critical the 'deadness' of most rooms means they should be (relatively) highlighted. I'd probably also prefer an algorithm that rarely gives out +2's (but might be aggressive at categorising -2s/-1s) so that it retains the existing workflow of allowing people to scan the list and give absolute highest priority to matchups they consider important. 

I wonder (as a part of this) whether the importance field could become a float (from a backend perspective) to allow a more granular order between debate ranks; even if from a user perspective it snaps to integers (having more than 5 steps I think complicates importance assignment too much).

**Comment by czlee** [comment]
I'm not entirely sure what's the idea behind the top-third/middle-third/bottom-third criterion. Would it work if we just had a simpler formula based only on liveness, without reference to bracket? I think I'd prefer something closer to the simpler formula you had originally:
- If an entire debate is dead, make it -2.
- If any team in a debate is live (not safe) **and** there is at least one entirely safe debate, make it +1.
- Otherwise, make it 0.

I could list critiques of any more complicated model, but the main reason I'd prefer a simple formula is so that it can be quickly explained to adj cores in a pop-up, so they (hopefully) feel more comfortable/nudged into adjusting things.

On when this should be done, I don't really have strong feelings about this. I guess doing it at draw generation might be easiest, though it'd be nice (not essential) to have a pop-up draw attention to what happened in the first round where not all debates are 0. (Why would doing it in an explicit step prevent the need to recalculate break thresholds?)

I'm happy to make importance a float in the backend regardless of whether non-integers are actually used.

**Comment by philipbelesky** [comment]
So the intent of the top/middle/bottom criterion is so that in the rounds before anyone is 'dead'/'safe' for a given category you still want to be able to differentiate between the debates, with the general preference for higher-point rooms getting higher importances. 

That said maybe there could be a shift between the two systems at some point (once teams start being marked as dead; or say when more than 10% of teams are dead) at which point it starts using your system or something similar that distinguishes primary on liveness rather than on bracket.

Just pondering now, but another way to handle things (in a way that is probably relatively intuitive) is to sum the liveness of each room and then split that into 1/3rd brackets. So the rule would be say "during the first 4 rounds, -1/0/+1 corresponds to bracket-thirds" then "during the final 4 rounds, -1/0/+1 corresponds to liveness thirds".

Doing it as an explicit step as part of adjudication allocation would mean that it could use the front end's representations of liveness (and then immediately update the front end) so it would avoid having to run all the queries again. 

Having it as user-initiated step would also allow people to retain full control of the importances if they desired. It could also be a way to navigate the above options, whereby there is a button for "Auto-allocate importances based on bracket" and "Auto-allocate importances based on liveness" and users can opt-in to whichever method they feel is more effective.

**Comment by czlee** [comment]
Hmm, maybe. For the first two or three rounds of a tournament (when everyone is very live) it's not really clear you'd want to differentiate between the debates at all. Like, I think it'd be erroneous—or at least questionable—to prioritize 3-point rooms over 0-point rooms for round 2, because (in a sufficiently large tournament) presumably those who happened to take a loss first round shouldn't have their chances of recovery impaired (with lower-ranked judges) so soon (_i.e._ be on the lower end of an incumbency advantage). So to me, the point at which teams start being dead is also the point at which you'd want to start distinguishing at all.

Similarly, I think it's questionable whether a room with three live teams should be treated as "more live" than a room with one live team. I can see why one might jump for that, but if you asked that one live team whether they were happy getting a less-qualified judge than their rivals, just because there happened to be more of the latter in the same room, I don't think they'd answer in the affirmative. I'd think they'd argue that they deserve just as much of a chance as their peers who happened to be drawn to the same room, and I don't think that's an unreasonable argument.

Of course some adjudication cores might want to have very granular scales for debate importance. But given how widely opinions vary on these matters, I think we should err on the side of more naive, and more readily explainable systems.

Re explicit step: I think those are good reasons why it should obviously be available as an explicit step. Thinking about it more, whether they should _also_ be auto-assigned on draw generation is a different question. A reason we might not want to do this is to try to make adjudication cores conscious about the fact that these importances are being assigned.

I'm also fine with having both bracket and liveness options, provided that they're both simple enough to be explained in a couple of sentences. This isn't too hard to envisage: "brackets" would just allocate on a linear scale according to bracket, possibly rounded, while "liveness" would do what I proposed above. I'd advocate presenting them as a mutually exclusive options (even though one could imagine systems for combining them, like yours).

**Comment by philipbelesky** [comment]
Yea, to clarify, I'm not speaking from my own perspective on how importances 'should' be ranked but more a revealed preference on how most adjudication cores have utilised the system thus far. 

The cases where you might want to give extra priority to a 2nd-round room where teams had a 'hard' matchup in R1 or where there is only one live team are definitely something adjudication cores check for (and would assumedly continue to do so regardless). The intent here is to save time by providing a first-pass assignment for the majority of cases where importance is (based on my observations) mechanistically assigned via general state (in terms of liveness/bracket) rather than an adjudication core's particular priorities or knowledge of the specific teams. Which, I am aware could backfire, but I think it's worth testing out.

**Comment by czlee** [comment]
Oh, sure, I didn't mean to argue against a manual override. But I meant that there's a good case against automatically prioritising any rooms in the second round in a systematic fashion, which is what anything we program would do. It follows that I think liveness should be the only _mechanistic_ determinant, and that there should be exactly three states (-2 for dead, 0 for safe, +1 for live), and the mechanistic automatic prioritisation in round 2 should have the net effect of doing nothing (as it would under my proposed scheme, since all rooms are live).

Since prioritising by bracket is a natural (albeit flawed) thing to do, and is easy to implement and describe, I'm also fine with providing the option.

I'm confused about revealed preferences with greater granularity than that, since I've noticed a range of opinions on finer details (and conventional wisdom probably also varies by region). Would a straightforward three-point (-2/0/+1) liveness scale (or linear prioritisation by bracket) be sufficient for a first-pass assignment?

**Comment by philipbelesky** [comment]
Yea, the question of granularity (for both brackets and liveness) I'm unclear about. Very rarely are the cases where an importance is set to -2 subjective; i.e. it seems to be used for obvious cases such as dead rooms. However cases where an importance is set to +2 are deeply subjective. 

Depending on how the algorithm looks in practice I could see either a three or four point scale working, but it seems like it should always start from -2 and work its way up (but never go above +1 so that +2 is preserved as an absolute override).

**Comment by philipbelesky** [comment]
I'm closing this as I think the current implementation (assuming it works correctly) is probably sufficient for this purpose; or at least is viable enough that seperate improvements and feedback can be discussed as seperate issues.
