### ISSUE TITLE
Add support for preformed panels

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#355]
Requires a new section of the front-end interface, as well as significant changes to the allocation algorithm. If being attempted, it would be good at the same time to work in bans/locks for particular adjudicators.

**Comment by philipbelesky** [comment]
Thought: panels should also have a specified importance (minimum or maximum value) to speed draw allocation. And that would be much more useful if Tabbycat had intelligent auto-ratings for importances.

**Comment by czlee** [comment]
lol that's a lot of milestone bumps

Thoughts:

### Workflow
You do preformed panels before results of the previous round are entered, and before the draw for the round in question is generated. But you need to have checked in adjudicators. This sort of interferes with our current workflow, so I'm not really sure where to put this?

### Database schema
Our current model of `DebateAdjudicator` requires a `debate`. While in principle we could make blank debates (without teams), I think that'd wreak too much havoc. I'd suggest that we want to store preformed panels in their own table, say, `PreformedPanel`, with its own model linking panels to adjudicators via another model `PreformedPanelAdjudicator`. (We could do this with a `ManyToManyField`, but we'd need an [intermediate model](https://docs.djangoproject.com/en/2.0/topics/db/models/#extra-fields-on-many-to-many-relationships) for extra data, and I don't know that I'm a fan of this pattern…)

Somehow, we'd need to link preformed panels with (not-yet-existent) debates. A few ideas:

1. Identify preformed panels by **room rank**. When matching, sort debates by room rank, and pair off from the top.
   - **+:** Simpler and less prone to chaotic edge cases, because you literally just pair off.
   - **−:** Really naive.
   - **−:** At the boundary, a live room might get a dead panel, or a dead room might get a live panel, and it might not be super clear that this is the case.
   - **−:** It wouldn't make much sense for round 1, where room ranks aren't assigned.

2. Identify preformed panels by **bracket**. When matching, allocate panels to debates in that bracket (randomly).
   - **+:** Easier conceptually to match panels to the _intent_ of the adj core.
   - **−:** It can be hard to predict _exactly_ how many debates are in a bracket (you might be off by one), at the top/bottom of draw in late rounds, it can be hard even to say what the brackets will be. This means bracket mismatches are likely to be common place. In order to be predictable, I think we'd just to just not pair such panels—which means in the ordinary case, a couple of panels/debates will be left unpaired; in some cases, a lot might be. (On the other hand, we could do a crude pairing and have the UI highlight mismatches.)
   - **−:** If there's a mishap by which brackets are all off or not labelled or something, this will just explode.

3. Identify preformed panels by importance (on a five-point scale). When matching, allocate panels to debates of the same importance. (This can still use auto-prioritize by liveness/bracket; the point is that the _system_ thinks of panels in terms of importance.)
   - **+:** Meshes more nicely with our current paradigm (at least arguably).
   - **+:** More human input into what is intended with a panel.
   - **−:** More human input required regarding what is intended with a panel.
   - **−:** In particular, it's on users to make sure the number of debates at each importance level (approximately) matches the number of panels with that importance. If this isn't the case, again, to be predictable, I think we'd have to leave mismatches unpaired. If the user doesn't match the importance distributions properly, this could be a lot of them. (On the other hand, we could do a crude pairing and have the UI highlight mismatches.)
   - **+:** On the other hand, this allows humans to actively use judgement to avoid such mismatches, in contrast to brackets where you're at the mercy of last round's results.
   - **-:** If we use a five-point scale, this might not be enough granularity.

Note that in both cases we'd have to deal with the possibility that the number of panels and number of debates don't match.

Then `PreformedPanel` would have fields `round` and `room_rank`/`bracket`/`importance` (whichever we choose as above). `PreformedPanelAdjudicator` would have `panel`, `type` and `adjudicator`. It might make sense to manage this with an analogue to `AdjudicatorAllocation`, or even abstract it so it can handle both debates and preformed panels.

### Allocation algorithm
We'd allocate panels to debates, which is an [assignment problem](https://en.wikipedia.org/wiki/Assignment_problem). Since preformed panels don't account for team conflicts, it probably makes sense to put some basic intelligence into how panels are assigned to debates:

- If we use room ranks, we could do a one-up-one-down swapper similar to the one used for Australs draws.
- If we use bracket or importance, we could run a Hungarian allocator within each bracket or importance level, where costs are determined (only) by conflicts.
- I guess if we're going Hungarian, for bracket or importance we could also run a single allocator over the entire draw, with penalties for bracket/importance mismatches.

-------

I didn't know this before I started writing all that, but I think my current inclination is:
- Identify preformed panels by importance
- Auto-prioritize by predicted brackets or predicted liveness (I don't know how to do this yet but I'm sure it's conceptually possible)
- User interface somehow indicates when assigning debate importance how many panels are at each importance level
- Use a single Hungarian allocator to match panels to debates with penalties for mismatches and conflicts
- There will definitely be importance mismatches as a consequence, so highlight them

I don't have any non-obvious thoughts about UI, other than highlighting suggested above.

Thoughts?

**Comment by philipbelesky** [comment]
Joining in on the thoughts

#### Workflow - preformed panel formation

To my mind this would be a separate 'roundless' section or sub-section, like Checkins or Setup. Essentially a collection of preformed panels would have a state detached from the round — at any point you can created or modify those preformed panels as well as being able to clear all of them and start fresh. It might also be useful in some cases to alter last round's preformed panels rather than starting afresh.

In terms of actually creating the preformed panels, at Mexico at least, there seemed to be a strong preference for the interface to present an as realistic as possible simulation of that future draw. The idea was raised that rather than just show the previous round's draws to actually go further and show a simulated draw (randomly assigned points) so that the brackets were as realistic as possible. 

I'm not sure we need to go as far as that given we are designing this system from scratch rather than transposing from a fake draw. Further, if allocating panels through the filter of importance, it might actually be a harmful mental model to present a fully-realistic draw in the UI. So perhaps, rather than showing a fake future draw, or the previous round's draw, it could show an series of individual matchups, but with anonymous teams, with each matchup having a pre-assigned importance value (and with clear breaks between each importance level). Pre-formed allocations would then proceed roughly similar to the way a normal manual allocation works. This would probably be the easiest to implement and work with, but poses problems for how we determine the number of matchups at each importance level that form the 'targets' for preformed panels:

- If the importance values are mapped by-bracket we probably want to figure out what the future brackets look like (i.e. do some form of approximating future results) and work backwards from those to generate fake matchups with importances that roughly map to what it would look like in the future draw.
- Would this method also need to be able to simulate importances assigned by liveness? If so it would need to work backwards from the future results and how they affect liveness, which would involve a good deal of uncertainty.
- If it could do both that would kind of be ideal, as we could then replicate the 'auto-prioritise' step currently used in allocation and have the two share the same code and conceptual model
- This method kind of assumes that the effect of manually-specified importance overrides balance out — i.e. the for every bump up in importance there is usually bump down. That is to say the overall distribution of importances within the range is relatively constant even after being manually tweaked.  If they are too far out of whack then forming panels against them becomes less meaningful.

#### Workflow - preformed panel allocation

In terms of the allocator, I was imagining that the 'unallocated' panel would essentially be subdivided, with one portion containing the standard unused adjs list and the other portion containing preformed-panels. Once #353 is completed, a panel 'unit' (whether that is preformed or a panel in the debate) would essentially operate the same way; you can drag panels between matchups and drag to/from the unallocated panels area. You would probably also need to be able to remove adjudicators from a panel; i.e. drag them from an in-place panel or from a preformed panel into the unused area or another debate.

At this point I'm unclear whether it would be better to fold the allocation of preformed panels into the standard Allocate button/action, or to have it as a separate step. Having it as a separate step would probably require #508 to be implemented.

I suspect if using pre-formed panels people might opt for manual allocation, but in terms of how the allocation algorithm works my preference would be for replicating the existing logic/workflow used by 'normal' allocations — i.e. it matches according to importance values as you also prefer. Given we have a means of assigning importance via bracket/liveness/manually, this seems like the most flexible option and one that maintains a familiar workflow. 

Preformed panels could be distinguished by showing their importance value inline as part of #478 (and probably use the same means of identifying when they are allocate to a different importance than specified)

#### Misc

- Preformed panels should ideally be able to done simultaneously by multiple terminals; i.e. a fully async page. So it can be worked on as part of that effort. Its unclear if sharding would be necessary however.
- Related: the preformed allocator would ideally be implemented as a 'pseudo allocation' by the front end so should be able to share most of the same code base. 
- Proposed schema looks good — we just want to make sure it is possible to present it to the front-end in a manner that closely matches the existing debate/panel structure so it can easily fit in to the current allocation methods
- It would be good to get wider feedback on these changes (maybe I could do some quick mockups?) as I feel like existing methods are somewhat hacked together. Deviating from this familiar model is both a risk and opportunity.

**Comment by czlee** [comment]
### Preformed panel formation
I basically agree with you. In particular, to go back a step from your discussion: I don't really know what it means for a draw to be "realistic". There are some things about a draw that are quite well-known: the number of debates in each bracket after each round is known before the tournament even starts, within 1–2 debates. There are other things that aren't known at all, like exactly which teams are in which rooms. If you present a single simulation of the latter, you're liable to be wrong. So we should present the things that are well-known, and omit the things that are not-known. I think this is equivalent to what you said, just with different rationale, right? So I'd even go as far as omitting the team columns, since they won't be meaningful.

- We could predict future brackets (and hence use it to auto-assign importance). For the middle of the draw we should know this to within 1–2 debates. For the top and bottom of the draw it's a lot less clear (will the top team be undefeated or have lots a couple of points), but also less consequential (since you know it's the top/bottom 2–3 rooms anyway).
- We could predict open liveness (and hence use it to auto-assign importance), but not restricted-eligibility liveness.
- In neither case will we be perfectly accurate. We'll always likely be one or two debates off, because of pull-up rooms.
- The assumption is actually weaker than requiring that manual bumps up and down cancel out. We only require that the number of debates at each importance level in the preformed panels, is equal to the number of debates at each important level in the actual draw. So there can be lots of manual bumps up in the preformed panels, if matched by manual bumps up in the draw. On the other hand, even without manual adjustments, the predicted importances and actual importances probably won't line up _perfectly_, so we'll have to be able to handle mismatches anyway—it's just that, as you say, the greater the mismatch, the less meaningful the process.

### Allocating panels to debates
An "unallocated panels" panel sounds good. I'm also not sure whether auto-allocating preformed panels should replace or be alongside the existing auto-allocate button.

Random thought: If you drag an adjudicator into or out of a preformed panel, then the panel's importance level probably should disappear, right?

I suppose in principle it sounds like we want to keep the conventional and preformed allocation implementations as closely related as possible? They're obviously not the same, but I'm sure there's enough overlap for some DRY to come into play.

**Comment by philipbelesky** [comment]
I think the meaning of 'realistic' used mostly meant 'having accurate bracket sizes' so yea that fits within the well known criteria. 

Having a team column might still be useful if just as a way of displaying the 'simulated' information in place, such as "Live ESL team" or say "Team on 9 points". But maybe that's unnecessary; although it could make the implementation easier. As noted it would be good to keep each as similar as possible for both DRY and UX considerations. 

Not sure at what point a modified preformed panel would become a generic panel; at least in presentation. That might be more driven by the implementation — I'm not sure it matters too much after it has been initially allocated.

**Comment by czlee** [comment]
# Current proposal

**Note for those unfamiliar with Tabbycat:** Tabbycat uses "importance" to categorize debates for adjudicator allocation. Adjudication cores specify which debates are "important" (should get better panels) and which are less so, on a five-point scale. Separating this from liveness or bracket allows adj-cores to prioritize rooms according to their own policies. Nonetheless, for convenience, Tabbycat has "auto-prioritize by liveness" and "auto-prioritize by bracket" functions to use as a starting point.

**Terminology:** By "standard process" I mean the adjudicator allocation process that is followed when preformed panels are not used (_i.e._ the "status quo", of sorts).

## Key points

- When making preformed panels, CAs would use predicted brackets and liveness for guidance, but not teams, _i.e._ there will be no "fake draw".
- The primary means of "ranking" preformed panels would be by _importance level_, which is the importance level of a debate it would be intended for. Predicted brackets and liveness would guide _how many_ panels to do for each importance level. (Preformed panels would not be identified by room rank or bracket.)
- After the next draw is generated, the "auto-allocate" function will assign preformed panels to debates to match importance levels while avoiding team conflicts. (The usual manual adjustments would then follow, with a couple more features to help with treating panels as a single unit.)

## Workflow

### During round _n_ − 1

1. **Determine how many rooms after of each importance level.**

    The software would give an indication of how many rooms are predicted to be in each bracket, and how many rooms are predicted to be open-live. The adj-core can (if they wish) use this information to inform how many rooms should be at each importance level. The software can also auto-assign importances ("auto-prioritize") based on its predictions, similarly to existing "auto-prioritize" functions.

    _Restricted-eligibility (ESL, EFL) liveness._ I'm not really sure how one would calculate anticipated restricted-eligibility liveness for the next round, but if someone has a method, I'm all ears.

    _Note:_ We do **not** propose generating a "fake draw" to assist with adjudicator allocations. To me, this seems like a misleading quirk of superimposing the standard process on a different exercise. Some parts of the next round's draw are well-known without this round's results, like the bracket distribution (to within 1–2 debates). Other parts aren't known at all, like precisely which teams are in said brackets, let alone rooms. Our idea is to present the things that are well-known, and to omit the things that aren't.

2. **Allocate adjudicators.**

    This is similar to existing functionality, except that:
    - No teams will be displayed and no team conflicts will be accounted for.
    - Panels will be saved in a separate table of the database specifically for preformed panels.
    - The preformed panel _itself_ will have an "importance level" assigned to it, which represents the importance level of the debate it was _intended_ for.
    - Debate importance, bracket and liveness will be shown, as it is in the standard process.

    An "auto-allocate" function would be available and it would be the same as the auto-allocate function for the standard process.

    _Note:_ Our idea is that the preformed panels aren't _fully_ ordered, they're just saved as being "intended for a debate of importance level _ℓ_". (Importance is a five-point scale, but think of this roughly as "for a very important room", "for a live room", "for an unimportant room".) We think this should capture better semantics about adj-core _intent_, by noting where the "cliffs" were and ignoring differences between similar-quality panels. See step 4 below for how this information will be used.

### Before round _n_

(after results have been entered for round _n_ − 1 and the draw generated for round _n_)

3. **Assign importance levels to rooms.**

    Now that the draw exists, actual importance levels can be assigned to rooms, just like in the standard process (in Tabbycat).

4. **Auto-allocate preformed panels to rooms.**

    Rather than simply pasting the preformed panels over the new draw, we propose allocating preformed panels using some basic conflict avoidance intelligence. Panels will be kept locked together as a unit and assigned to debates with the same importance level (if possible), while at the same time avoiding conflicts with teams as much as possible.

    _Technical description:_ We propose using the Hungarian algorithm to assign preformed panels to actual debates (which is an [assignment problem](https://en.wikipedia.org/wiki/Assignment_problem)), with costs assigned for
    - mismatches between preformed panel importance level and debate importance level, and
    - conflicts with teams in the room.

5. **Finalize adjudicator allocations.**

    This is similar to the standard process, though with some new features planned that are sort of orthogonal to this one:
    - You can move entire panels as a unit (#353).
    - There'd be an "unallocated panels" section, similar to the "unallocated adjudicators" section, but for panels.
    - We'd go for some conception of simultaneous editing from multiple terminals, though details of that part are yet to be hashed out and are orthogonal to preformed panels anyway (_i.e._ would be just as applicable to the standard process).

# Database schema

`PreformedPanel` has a `round` and an `importance`.

`PreformedPanelAdjudicator` foreign keys to both `PreformedPanel` and `Adjudicator`, and has a `type`  field (chair/panellist/trainee).

**Comment by philipbelesky** [comment]
@czlee I mentioned this above but failed to notice this in the schema propsed: do we want panels to have a foreign key to round rather than to be 'roundless' as I mentioned? To my mind it might be easier to essentially have a workflow where the panels are semi-consistent — i.e. you can choose to wipe and reform them but they could also be maintained round over round and instead be edited in place. 

Because the  `PreformedPanel` is essentially a pseudo-debate but one not dependent upon any round-specific characteristics it might be better to treat them as largely static objects. Their importances could be updated manually or automatically and estimates of what bracket/liveness they represent would be handled on the front end anyway.

**Comment by philipbelesky** [comment]
Also on a similar note should `PreformedPanelAdjudicator` track the allocated position? I think people would want to explicitly assign chair/trainee statuses.

**Comment by czlee** [comment]
Sorry, I didn't realize your roundless comments pertained to the database schema too. I think the UI can be outside the round workflow, but I don't think it's true that you would expect panels to be semi-consistent between rounds. In round 2, all panels should be more or less even; in round 9, they should most definitely not be. Moreover, you don't really want the same panels from round to round, because you want judges (to some degree) to be judging with different people in each round. A _specific_ panel isn't beholden to round-specific characteristics, but the _set_ of panels relating to an entire round are. In my head the "round" field would allow us to save (for historical record) what panels were used in round 2, without destroying them when we start round 3.

I guess what I'm proposing is really just a versioning scheme, so we could even go a step further and allow the adj core to save "versions" as they're working on it. We could do this with or without rounds—like, we could just name versions with strings—but I was thinking having "round" at least as an optional field would allow us to keep track of what's going on afterwards, or filter versions by round.

It's worth noting that maintaining a round field doesn't preclude copying the previous round as a starting point, which I agree would be a good idea in some cases. But not all cases—I think the auto-allocator would often be a better starting point, particularly in the late inrounds.

Re chair/trainee, that's what the `type` field is for, named to mirror `DebateAdjudicator.type`. 🙂

**Comment by philipbelesky** [comment]
Ah not sure how I missed the `type` field.

Hmm, yea encouraging maintaining patterns round over round is probably an anti-pattern that would lead to poor adj rotation and having people adj together often. Versioning might be a little over complicated, but if it's linked to rounds they could essentially play this role — i.e. you could copy from a specific round as essentially a 'fork' of that version.

I'm still a little unclear about where this sits within the navigation, although thats a relatively minor problem. It's a round-specific action but one that sits outside the critical path. 

- It could go in the per round sub menu before availability but then that might be confusing to people who don't understand or want the feature. 
- Alternately it could live within the `Draw` tab like the normal allocation, which isn't very discoverable. That might be fine given its a feature for experienced tab directors. 
- It could also be a top level item in the main menu, but it would then need to be subdivided by round which is strange given there are also round-specific menus. I'm not sure it needs this level of prominence either. 

Another headache is how this interacts with availability, particularly as it would likely be used before availabilities are known. Would it only allow adjudicators marked as available to be preformed into panels? How are updates to availability reconciled with it? One way to compensate for this would be to have a warning on the draw page or in the allocator that indicates if an adj is allocated but not available.

**Comment by czlee** [comment]
Yeah, I had similar questions, and no clear answers. Of those three alternatives, I think the second seems the best to me—I don't mind sacrificing discoverability a little bit. Or a lot, really, since you'd have to go _into_ the _next_ round, past a bunch of warnings asking why you haven't completed the previous round yet, in order to find it.

With availability—nowadays I find I often preload availability anyway, either loading all availabilities at the beginning of a tournament (so I don't forget), or going through the list _during_ the previous round (particularly for host institution adjudicators, which while planned often need real-time adjustments). Which is to say, I feel like availability's place in the workflow is pretty fluid and tournament-dependent. Which doesn't help us much here… other than to say, having the warning on the draw page if an unavailable adjudicator is allocated, _or_ if an available adjudicator is not, is probably a good idea anyway, and might even be the best we can do?

**Comment by czlee** [comment]
Oh, and I guess if I find availability is often (mostly) known ahead of time, then I also think preformed panel choices should be limited to available adjudicators (then fixed later manually if availability is changed). 🤷
