### ISSUE TITLE
Allow adjudicators to verify their confirmed ballots online

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#400]
It would be interesting to investigate if adjudicators could be shown a 'verified' copy of their ballot(s)  once the paper ballot was entered and/or an eballot confirmed against a paper copy. Obviously, the primary use would be to better check data integrity.

The problem becomes when to make this available to them (ASAP? Post round-advancement?) and then how to notify them of that fact (technically we could email/SMS them but that is unlikely to be of use at internationals). If we can only prompt people to access it when a round is 100% complete then it's unlikely they could check things before the next round is drawn. 

That said, even it enables a-little-too-late-to-be-convenient checking of a ballot that's possibly still better than not having this ability.

**Comment by czlee** [comment]
One question is how we'd authenticate adjudicators, since it's (at some tournaments) quite important that ballots not be accessible by anyone else. A few options:

1. We could attach it to the current system, whereby adjudicators have access to unique and unpublished random strings in URLs. But this isn't very secure. It might still be secure enough: is security of ballot viewing more or less important than security of feedback submission?
2. We could have adjudicators log into accounts. This requires us to build add support for participant user accounts though, and comes with all the human-logistical problems associated with making participant user accounts.
3. We could _only_ push-notify people (e-mail/SMS, as you said), then authentication exists "by default" in that we only have to regulate people's contact information. I'm not as convinced that this would be useless at internationals, if enough people sign up for them: some people will be on roaming and be able to receive SMS, just not send; others might get onto Eduroam and get push notifications for e-mail. It won't work for everyone, but it might work for enough.

**Comment by tienne-B** [comment]
This task is continued by #502 for point 2 and #535 for point 3. The pull request #626 takes the email approach with immediate availability so that errors could possibly be fixed before being used.

This task could possibly be closed after that pull request, but this task may be greater, for a (read-only) ballot view as a URL, not just as a form.

**Comment by czlee** [comment]
Hmm, #502 isn't really about point 2 (which still only envisages accounts for tab staff and tab assistants), but I agree that #535 is the same as point 3. I'm not really a fan of idea 2, actually.

I'm personally comfortable with just point 3, but there's one good argument I can think of for the read-ballot view, which is that it would always reflect the current database content (however it's been edited), whereas the emails will only send what was confirmed at the time of confirmation. I don't think a mismatch will arise very often in practice, but it's possible in principle. They're not mutually exclusive, of course; since (3) is already in there, the only question is whether we want to do (1).

It wouldn't be very difficult—it's mostly just putting an existing view (the scoresheet view) at a new URL (the randomized one), plus putting in a meta tag to prevent it the URL from being indexed by web crawlers. (Okay, it's a bit more than that I guess, because you'd want to have every round accessible.)

@philipbelesky, thoughts?

**Comment by philipbelesky** [comment]
Hmm yea, I guess in theory this sounds like some sort of security risk where adjs could easily publicise what scores they gave etc. But that capability already exists and norms seem sufficient to stop it happening as-is.

So yea, I'd be happy to have a secret-key style URL for each round's result. You might get slightly more uptick / reliable results sending the results in an email (one less click for users) but the data changing later is an issue. Potentially we could even do both: send a summary of the results in the email; and also ask them to follow a link an verify it if anything looks odd?

**Comment by czlee** [comment]
Yeah, I agree with all of that. So there exists _a_ benefit to (1), mainly it's then a question of whether (1) is worth the effort, I guess.

**Comment by tienne-B** [comment]
This was implemented with #957 (11361a805054202ac104d9280b543046c41c9f46) using private URLs and providing access when confirmed.
