### ISSUE TITLE
Change assistant pages to use /assistant/ rather than /admin/ + allow admin access

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#510]
I'm a little on the fence about this, as it would mean duplicating a lot of the `urls.py` code, but I think it makes sense from a semantic perspective to indicate which level of user access is shown in the URL. A number of context processors for navigation highlights now also break because they can't easily distinguish between admin and assistant.

It could also mean that we could then potentially also duplicate the Views into ones that are dedicated for Admins-only and Admins+Assistants, such that an admin could say access the assistant version of the ballot entry form (rather than having to create a new account).

**Comment by czlee** [comment]
I think it's not a bad idea. Having class-based views means this wouldn't be too problematic from the views side and in some cases might make things a little simpler, since it means we can use subclasses/subtemplates rather than if/else statements. I'm definitely sympathetic to the idea of admins being able to access assistant views.

**Comment by czlee** [comment]
I think this qualifies as done now (on the develop branch); if anything's broken, can fix as it arises.
