### ISSUE TITLE
Make adjudicator allocations hidden until released

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#517]
This is minor, but: If you want to allocate sides while the adj core is still allocating panels, and show the side updates in GA, it'll also show the work in progress on adj allocation, essentially live (every time you refersh the page). It'd be a small but nice improvement to be able to hide them.

Now that I think about it, I'm picking that there are probably other cases where you want to release team pairings without releasing adjudicator allocations.

I wouldn't do this if it's very hard, but maybe a system similar to draw and motion release might be useful? But we don't want to break the standard use case when they're released simultaneously, so there might be some UI questions.

**Comment by philipbelesky** [comment]
Which page is being used to show the side updates? The public draw page; or the admin one? 

Potentially we could add a button on the front end to hide the adjudicators column, but I wouldn't be super enthusiastic about adding another step to the critical path for a niche use case.

**Comment by czlee** [comment]
Umm, I think I was using the admin one, but anything that's up in GA you want to be available publicly anyway?

I don't think this should be on the critical path (in fact, I think it should not be), they should probably be released (or just "visible") by default and maybe we have a button on the adj allocation page to hide it or something.

**Comment by philipbelesky** [comment]
Yea, or if its only desirable for admin use we could add another "Draw Display By..." option that excludes the adjudicators column by default. That's probably safest and simplest as there's no need for a button to hide things post-load.

**Comment by czlee** [comment]
Hmm, maybe. I was thinking it would also be nice to be able to show outround pairings without judge allocations, as soon as it's obvious what they would be.

**Comment by philipbelesky** [comment]
If it's just for out rounds it could almost be a brackets-style diagram of the elimination stages? But that might be a bit overkill.

**Comment by czlee** [comment]
I think a bracket diagram would be cool, but different. If your objective is to figure out which venue you want to go to and who's in which position, bracket diagrams are a little harder to parse. (If your objective is to see when teams will first meet, bracket diagrams are great.)

**Comment by 0zlw** [comment]
Hi all, I had a go with working trying out the "hide adjudicators" feature in v2.4.0A over the weekend and generally found the fix didn't satisfy how we were hoping to using Tabbycat. 

I think it's somewhat common for tournaments to want to release the draw ahead of adjudicator allocations and then use prep time to complete adjudicator allocations. This is a particularly useful tool when trying to run smaller tournaments to time (i.e. non majors) or where judge allocations and conflicts are less important.

At the tournament (60 teams) that we were running over the weekend, we were releasing the draw, giving teams time to organise themselves correctly on Zoom, then about 5-10 minutes later releasing the motions. Often the adjcore did not have judge allocations ready under 15-20 mintues into a 30 minute prep.

As tournaments move online, we are much more dependent on using public released draw pages to communicate the draw to participants, especially if a tournament isn't using a platform with screensharing (mixidea/discord/yaatly). 

To that end, it would be helpful to have an option to separate out the public release of the debates from the adjudicators.

I understand concerns about disrupting core workflow - could this potentially implemented via a configuration checkbox that if on then separates out the "release draw" from "release adjudicator allocations" on the display screen?

Interested to hear your thoughts on this as I know you just implemented a commit in this area.

**Comment by philipbelesky** [comment]
Yes, I can see why that new page is not particularly useful in the context of online tournaments in particular. This is rehashing earlier comments, but to my mind there are two options:

#### Adding a separate release flag for adjudicator allocations

This probably wouldn’t be too much extra friction once people get used to it. It probably also has a much higher likelihood of getting people to realise this kind of workflow is possible. 

The implementation would need to be careful about non obvious pages were allocations may be revealed, e.g. private urls.

As a side note, I guess there would also be a case to be made conceptually for venues to also be released manually per round? I’m just not sure what the value would be. 

#### Adding a preference to enable an adj-less public draw

This seems like it would still need some sort of trigger to switch over to the normal public draw once allocations have been released. Otherwise there would just be two public draws floating around all the time? So in practice it would need the kind of flag mentioned in the first option. The only automatic logic I can think of would be having matchups be published immediately after they are generated which seems dangerous. 

Thoughts @czlee @tienne-B?
