### ISSUE TITLE
Team importer always imports use_institution_prefix as False

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#523]
In the `init()` method of `TeamDetailsForm` form it does the following:

        if self.institution_for_display is None:
            self.fields.pop('use_institution_prefix') # For Instition-less teams

When the form is first populated this works as intended and removes the institution prefix field only for unaffiliated teams. However when the form is submitted again it seems to redo the `init` step but in doing so `self.institution_for_display` is always `None` so it actually removes that field even when it has been set. 

@czlee I've tried to find some other variable here that represents the lack of institution and persists across both submissions but haven't had any luck. Any ideas here? I'm not super familiar with how the forms implementation here works.

**Comment by czlee** [comment]
Sorry, when you say "the form is submitted again", do you mean that there was a validation error the first time? Or is this on the clean beginning of a new form?

**Comment by philipbelesky** [comment]
On the clean beginning of the new form. What I think I mean is the init() is called by the view that shows the blank team form, but then also when that form is submitted.

---
Philip Belesky
Associate Lecturer, Landscape Architecture

School of Architecture and Design, RMIT University

landscapearchitecture.rmit.edu.au, philipbelesky.com

**Comment by czlee** [comment]
Oh, right, yeah, that sounds right. The comments in [lines 183-184](https://github.com/TabbycatDebate/tabbycat/blob/ca056a03dd50f8f4adc92c811821bd52ac43af57/tabbycat/importer/forms.py#L183-L184) indicate that that attribute isn't used in the form logic, I think that's why.

I'll have a think about it in a couple of weeks.

**Comment by czlee** [comment]
Wait, `institution` is a field on the form. Can't we just use that?

**Comment by philipbelesky** [comment]
I had tried doing that initially, but wasn't able to get the value of the field. I was probably doing that wrong though.

**Comment by czlee** [comment]
@philipbelesky Just an FYI, the answer was to check `self.data` if `self.initial` was empty, which is what it previously did, but you had removed it in https://github.com/TabbycatDebate/tabbycat/commit/b5f5cdee53d73212f53085afac70cc457e73ffee#diff-77e753ae5d63e1b21bdf2b731f800ca5L184. Fixed in 9cdf692.
