### ISSUE TITLE
Add method for integrating checkin systems with external methods (i.e. barcodes/QR codes)

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#526]
This could be as simple as testing that the existing end point can be posted to by an external service; but we should probably get an idea of how those services would work and ensure the implementation works to a proof of concept level.

**Comment by philipbelesky** [comment]
So, I'm slightly hijacking this issue to cover 're-addding this old checkin system', but on that topic, how did we want to model the per-person checkins as compared to the existing checkin system. Misc thoughts:

- Existing 'checkins'  serve a dual purpose in tracking who is or is not present, and who should or should not be included in the draw. 
- The new checkin method would be just a record of physical presence, but would likely not be recorded across every single round; more likely at the start of each day etc
- What do we call the new method? Perhaps 'available' or 'attending'?
- Is the new checkin system linked to individual rounds (as with the current system) or should it be possible to create some sort of AvailabilityPeriod that maps to multiple rounds (i.e. a day)
     - This would be a more complex option; an alternative would be to instead always show in which round (or perhaps a particular timestamp) when the user last was recorded as available/attending
- The existing checkins page should probably show the 'attendances' in a manner that makes it easy to have them inform the existing checkins
- This affects #391 in that its unclear if that should show both the existing checkins and/or the new checkins

**Comment by czlee** [comment]
I have no idea. I also think that the use-case varies a lot by tournament. North America, for example, has blindsided me with its habit of having the host's debating society members double as both volunteers and judges, and its tendency for institutional judges to go MIA.

I'm a fan of detaching physical presence from who is getting paired in, because they're different and they don't perfectly correlate. But the way in which they do or don't align seems to vary by tournament, and I can't precisely enumerate how.

I guess if we want to make this reasonably general without being useless, _maybe_ the following are common elements:

1. Attendance and check-ins are not the same thing. But with that in mind, if "check-in" means "going to be paired into the draw", the names "check-in" and "availability" are both confusing. Maybe we should describe "going to be paired into the draw" for what it is, like "Teams to include", "Adjudicators to include", "Venues to include". Tabbie2 uses "active" to describe this, which also works for me.
2. The transfer between (1) previous round check-ins, (2) attendance logs, (3) _anticipated_ availability (when adjudicators in advance that they won't be available for particular rounds), as well as other sources, should probably be manual—otherwise there's no way we'll cover all cases.
3. But if it is manual, then we'd better have a good UI for "merging" information. Right now I do this by having multiple windows open.
    1. On this note: Independents, home judges and institutional judges are each a little different in nature, so in my ideal world I'd be able to deal with each of them as separate categories. But I think that's locale-specific, so the feature shouldn't be "you can filter by each of those three categories"—some clever column sorting would do the trick.
4. My current experience with morning attendance registers (based on two North American tournaments) is that a spreadsheet is easy enough to manage. But I don't think a one-size-fits-all approach is likely to work. For small tournaments you just have a list of everyone on the same screen; for large tournaments that won't fit. Typically at the top of the screen I'll write something like, "Check in at the front, absent teams will be dropped at 09:00." For WUDC there's no way this is a good strategy. I _think_ what I'm trying to say is that I'm not even sure I would bother building in an general-purpose attendance mechanism into Tabbycat, unless I can be satisfied that there's a good general solution.
5. Availability periods that link multiple rounds is probably overkill. Better to just have the user select when they care about attendance logs, and specify for which round (e.g. "for round 5, use the attendance log for round 4").
6. In fact, the more I think about this, the more I convince myself that trying to write a general solution is a bad idea. Better to make it easy to transfer availability information from somewhere, whether third-party software via REST API or a spreadsheet via CSV/TSV copy-paste, into the tab.

This takes us back to the old barcode check-in system: a very simple implementation is probably a nice convenience, even if it's not the "correct" place for it to be. In that case, what should it look like? If I think it should be a separate function, then:
1. It should be in its own app, with its own models and views.
2. "Own models" _includes_ the barcode ID itself, which should _not_ be part of `Person`.
3. It would mean whatever the user wants it to mean, but in practice, probably "attendance".
4. Either you do it by round, or you just have the user create a new "attendance log", completely independent of rounds. The latter might be easier to avoid unintended side effects with future development.
5. We could provide various convenience functions to set present participants as available, or set absent participants as unavailable (these are not equivalent), or both. But as discussed above, I think in many contexts this will be too simplistic.

**Comment by philipbelesky** [comment]
Just focusing on the old barcode style check-in part as that seems the part that is more immediately required:

1. Happy to keep this to its own app, though philosophically it seems like it would fit within the general remit of `availability`? Thats not a particularly large model in terms of what it contains either
2. By this you mean I assumed `Barcode` objects should be a distinct model; but presumably linked via a Foreign key to `Person`? Although I guess there might be the option to link to say a Ballot or a Room in a way that supports an API type system for those things.
4+5. Perhaps at this point it might be easiest just the the act of registering attendance just marks a timestamp, and that views such as 'missing people' or whatever translates attendance-to-checkins is intelligent (or configuring) as to what gap in times constitutes a timeframe. So for example a gap of greater than say 20 hours is would not copy across to a checkin.

**Comment by czlee** [comment]
1. No, on reflection, I don't think so. Like, I can see how they're tangentially related, but one of them is about indicating who you should pair into the draw, and one of them is about scanning barcodes so you can figure out who's scanned their barcode.

2. Correct. `Barcode` would have a foreign key to `Person`, and a field for the barcode.

3. —

4. That's a good idea! The gap would probably be more like two hours (a round's worth), ideally with manual override, but yeah I can see how that'd be simpler to work with than having to create an attendance log and so on.

**Comment by philipbelesky** [comment]
Hmm, ok, so I was going to get start on this but having some trouble thinking about names for both the app and the front end. 

#### app-name

I guess this doesn't matter too much, and my preference would be to keep `availability`as-is. In which case what would this app be called? `checkins` would be my best guess (or would that be `check-ins` / `check_ins`)?

#### ui-name

So, I think if we were designing things from scratch, a barcode/QRcode/token system would be labelled as a 'check-in' for the purposes of the UI. Problem is we already call `availability` related things 'Check-Ins' on the front-end (mostly). As you mention above this is more like an `active` or `available` status. 

It would be slightly jarring to swap 'check-ins' to 'availabilities' in the front end, but probably not hugely so — the only change is really in the side menu, and the overview page (plus the docs). It could  technically be a backwards incompatible change, but in workflow terms the actual actions necessary remain the same.

Thoughts? I was thinking this was a tricky choice but upon writing out I think I've convinced myself.

**Comment by czlee** [comment]
On app name, I was thinking maybe `attendance` or `scanning`, since that's what it's for. `checkins` is also fine.

On UI name, I don't have strong feelings about this. Also I don't mind renaming "Check-ins" on the front-end, even to "Availability", and I definitely don't think it counts as a backwards-incompatible change. As an aside, I always thought "availability" was technically uncountable and our use of the plural was nonstandard, though dictionaries say an availability is "something that is available" (so a person with availability is an availability).

I was meant to set up the database/models stuff this weekend but didn't get a chance. Do you want me to?

**Comment by philipbelesky** [comment]
Hmm to my mind `attendance` is slightly odd because the scanning process sometimes happens at say the accomodation or somewhere outside the venue that will be 'attended'. `Check-in` I think better matches the colloquial term used for this at big tournaments and probably conveys the intent of the process slightly better than 'scanning`. 

Feel free to go ahead with the database/models whenever you're ready; I probably wont get to it before you.

**Comment by philipbelesky** [comment]
I think it also slightly accords with how we use it to describe ballot check-ins which I'm still interested in trying to add barcodes to at some point.

As a sidenote, it would be nice if this new app could also potentially take responsibility of that process particularly as it relates to #410. The model under a `checkin` app wouldn't necessarily need to cover both `Person` and `Ballot` but there might be a set of shared methods / views / templates between the two cases.

**Comment by czlee** [comment]
I actually try to avoid debating-colloquial terms in software as much as I can, both because different circuits tend to have different terminology, and because more formal terms tend to describe what they are a bit better (than, say, "scratch" or "inround"). But "check-in" qualifies as a formal term, because it's the most standard term used for checking in at an airport or a hotel.

Re #410, agreed. It'd be a bit premature now but I guess in future we might spin out the common functionality to a third app that behaves like a package, that both `checkin` and `results` use.

**Comment by philipbelesky** [comment]
Misc mental note: if we are providing barcodes/QR codes for people to be scanned-in on it might not be the worst idea to also provide QR codes for feedback/ballots if desired. The idea being you could kill two birds with one stone by giving out a single sheet. Maybe.

**Comment by philipbelesky** [comment]
Heads up: I've had a go at the models for this and have pushed up the results. The one thing I was questioning was whether to have separate `Identifier` models for the different use cases between People/Ballots (and possibly Venues) or whether to use generic foreign keys (ala Availabilities). The later seemed cleaner, at least in terms of model implementation although I'm not sure how much more complicated it will make interacting with the model elsewhere.

**Comment by czlee** [comment]
Oh, that's a tough trade-off to make, I've heard arguments both ways. My rough guide was to use separate models when there are two, and generics when there are at least four, but even that's probably not right if there's not many circumstances where you want to deal with them all at once. For this I would've gone separate, if only because I think I've been overzealous about using generic foreign keys in the past.

**Comment by philipbelesky** [comment]
Hmm, yea, I might actually refactor them to be separate models just to make querying things slightly easier and because on the admin it makes for better separation and allows the foreign keys to entered without knowing the ID number. Thinking now I guess these should also be tied to `tournament`; if just for filtering purposes in the admin and to make querying slightly easier.

**Comment by czlee** [comment]
Hmm, I'm sure there are ways to enter objects into GFKs without knowing the ID number, but yeah I agree we haven't found them yet and it's currently annoying. I still don't think that should be the main factor though. I think the main factor should be whether you would ever want to look up lots of them of different types in a single query, because that's what GFKs allow you to do. I'm not actually sure if we do that even for availability. (For action log entries we certainly do.)

If we're talking different views for them and everything, maybe separate models, and implement common functionality in an abstract base model?

You can figure out what tournament it's from by indirect reference, can't you? Or at least once the models are separated (lol).

**Comment by czlee** [comment]
Thinking about it more, so in this case the question is: Would you want to pull a list of identifiers, for all content types in the same list, to display in the "identifiers" page? If yes, we should use GFKs. If they're just like independent concepts, we should use abstract base models.

Here's one article I once read that I think pushed me towards that idea (though this doesn't advocate it, it's actually even more anti-GFKs than my current position), and made me doubt that refactoring availability to use content types was a good idea (though I still stand by refactoring actionlog): https://lukeplant.me.uk/blog/posts/avoid-django-genericforeignkey/

**Comment by czlee** [comment]
Another idea: If it's important that uniqueness across _all_ identifiers be enforced at a database level, then we should use GFKs. But I sort of doubt this is necessary, it's what prefixes are for.

By the way, what's with the database-level six-character limit?

**Comment by philipbelesky** [comment]
The six character limit (it's actually also a six character minimum — see the regex) was me thinking that the unique identifiers should be easily type-able: so 6 alphanumeric characters is short enough to ensure uniqueness (assuming every person/venue/ballot across many big tournaments has one) but not being overly verbose while doing so. 

As for GFK I can't see the need to show content in the same list, so will do that refactor that splits them up with a base class. That said it would be nice to keep the `barID` identifiers unique across all models so that there could be a 'universal scan page' if it ever goes beyond just `People`.

**Comment by czlee** [comment]
I see, though is the six character thing a recommendation or is it actually technically necessary for the system to work? eg do barcodes all need to be the same size to fit in the printout? We can always make the autogenerated codes six characters, I was just wondering why we had to stop users from doing something different. (c.f. private URL keys)

How would you feel about using prefixes to enforce uniqueness? We do this for URL keys and it gives a human-identifiable sanity-check (so they can tell by looking at the barcode if it's nonsense), though I can see why one might consider prefixes an annoyance.

**Comment by czlee** [comment]
Actually, we can do uniqueness with non-abstract base models, if you like. Similar structure to `Person`—Django maintains a separate database table for `Identifier`, and does all the database joining behind the scenes. A slight performance hit, but I'd say not a prohibitive one.

I gave that a go (on the same branch), it does create some complications with code reuse (relative to GFKs), in that because the base class can't figure out which subclass is relevant, you have to maintain that information yourself. I was too lazy to duplicate the views (for now), so (for now) the identifiers view is just for people. Let me know what you think.

What are the venue barcodes for?

**Comment by philipbelesky** [comment]
Um, if implemented, I imagine the exact use for venue scans would be something that people could figure out in practice. My rough ideas of where it *could* be useful is as:

- A way to verify all rooms are unlocked/suitable (say at the start of the day)
- A way to verify that a room's ballot has been collected
- A way to verify rooms being live streamed or that have other sort of temporary significance during rounds

This is probably one of the cases where a QR code type system would be more effective than a barcode based one, although the plan was to have both options for all the different types of identifiers.

**Comment by czlee** [comment]
Okay, I have no idea how QR codes could possibly be imagined to help any of those processes, but if we're adding the ability to add barcodes to most objects for the off-chance that they _might_ be useful, that actually seems like a good argument for using GFKs, since then we could let barcodes be attached to (literally) any object in the database. I think this is mission creep though.

Re user control, the same argument you made applies to private URL keys actually. From memory I think that was just an implementation thing: Auto-generating was too hard to implement in a foolproof way.

For `DebateIdentifier` I think it's easy to make the auto-generated at the same time that the draw is generated, so certainly no objections there. It wastes database rows for tournament nearing the 10,000-row limit, but I don't really care if a few tournaments have to pay $9/month

**Comment by philipbelesky** [comment]
@czlee let me know if you have any thoughts on this; the current status of the implementation and documentation should hopefully give a pretty good idea of how I imagine the system working. 

You might also want to test parts of it at an actual tournament as well (say the ballot-barcodes or the check-in status page as a general-purpose roll-call tool absent barcodes). Current todo list looks like:

- [ ] Check physical barcode scanners work with the scanning form (mine should be arriving soon)
- [ ] Incorporate barcodes/ballot-checkins into the existing ballot printing/check-in system
- [ ] Tweak the existing Identifiers/Statuses pages to work for venues
- [ ] Tweak existing Status page to be a public optional page
- [ ] Integrate check-ins into the availability page
- [ ] Check live barcode scanner with android phone
- [ ] Basic selenium tests
- [ ] Basic view tests
- [ ] Basic unit tests
