### ISSUE TITLE
Allow next draw to be generated with unconfirmed (but existent) ballots

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#534]
Currently, we prevent draws from being generated before all ballots are confirmed. In some contexts, particularly where pairings within brackets are random (WUDC), it makes sense to press ahead before all ballots are confirmed, hoping or assuming that the results (not speaker scores) are correct. This needs to be done with various checks to prevent stupidity, though.

**Comment by czlee** [comment]
So the obvious easiest thing to do here is to change the rule for advancing so that every debate has a confirmed ballot, but doesn't necessarily have its result _status_ as confirmed. The confirmed ballot bit is technically necessary, because the next draw generator needs to know the result (not speaker scores) for the debate, which is contained in a ballot somewhere; since multiple ballots can be attached to a debate, the only way to identify which one contains the result is to confirm it, or another mechanism that is tantamount to the same thing.

This is great and is what I do in practice, but it's not very intuitive. The standard workflow is that a debate's result status is confirmed if and only if it has a confirmed ballot. But only the converse direction is enforced (you can't make the result status confirmed unless it has a confirmed ballot, but you can confirm a ballot without confirming the result status).

So it's not totally obvious to me how to make this nice, as opposed to just possible. Any thoughts?

**Comment by philipbelesky** [comment]
Hmm, we couldn't really make a ballot be automatically set to confirmed upon its result status being `DRAFT` right? That would break too many assumptions?

What's the imagined workflow here that needs to be made nice/possible? Like is the challenge just to maintain the current data entry workflow but (due to technical changes) allow for draw-generation sooner than we would now (i.e. when all rooms are at least draft)? Or is the challenge that we want to present an alternate data entry workflow which tab directors can opt-in to that allows them consciously mark ballots as 'good enough' for the purposes of generating a draw? 

I ask as it seems like the former points to some sort of solution in-between the standard results entry process and draw generation — I.E. a special "Generate Unconfirmed Draw" button or something that passes debates to the DrawGenerator as if they were confirmed. In this scenario everything happens as normal and the crucial choice is if/when a tab director wants to create the next draw by opting into such an 'override' option.

The latter seems to point to maybe some interface changes to how we present the 'confirmed' status in the standard ballot entry area. I.E. making it more obvious that (on a per-ballot basis) you can mark a ballot as `confirmed` (but keep its status as `draft`) if you want to skip final verification on it (to get to the draw faster).

**Comment by czlee** [comment]
Yeah. This is an excellent way to phrase the question. I think it's the latter—at least for me, I want to make a conscious call to run with the draw, knowing _exactly_ which ballots are potentially iffy, and hoping that any resolution of speaker scores won't change the result.

I guess one terminology issue that this question makes more obvious is that the `confirmed` field of a submission is a slight misnomer. What it _actually_ means is that the ballot is the version that is picked out to be "the" result of that debate, which it can technically be whether or not it's "confirmed". So like, `authoritative`? `canonical`? `controlling`? `prevailing`? A similar misnomer issue exists for feedback, now that we've decided not to implement #53, where (I've just realised!) we chose `confirmed` over `active`. Would changing the name of this field help?

On a tangent, I have some vague recollection, when I implemented that system, of being divided over whether to make this an attribute of `Submission`, or whether make it a foreign key of `Debate`. I can't remember exactly why I opted for the former, but I think it might've been to make filtering for confirmed ballots easier (on a Boolean rather than on a reverse foreign key).

**Comment by philipbelesky** [comment]
I like `canonical` as a name; at least for presenting to users. It more than the other names seems to imply that a result/status can be present but not official (i.e. non-canonical) and also that the same result/status can be disputed amongst multiple ballots but that only one can be official (i.e. that there is a single 'canon'). 

I also agree that we probably want to make this a tweak of the existing system, whereby you can pre-confirm (i.e. pre-cannonicise) a ballot in order to accelerate the process. So I guess the way to do so is to rework how we present that option on the admin version of the ballot form; maybe also add some documentation to this effect. 

On a backend level is the only change to allow round advancement when all debates have a confirmed/canonical ballot? Or is it more complicated than that.

**Comment by czlee** [comment]
Yeah, that's it. Nothing more complicated, at least for a first implementation, except that I'd want to double-check that I'm not conflating canonical ballots and result-confirmed debates anywhere that could cause harm once we start breaking that assumption.

("Canonical" also sounds most natural to me, but I looked the word up in a few dictionaries and none of them list the meaning I think it means!)

**Comment by philipbelesky** [comment]
Yea, the dictionary definitions are still very much in the Vatican. Looking it up in a thesaurus should match the common usage though.
