### ISSUE TITLE
Check/implement a conflict test for double-past institution conflicts

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#536]
IIRC we don't currently check/test for situations where a speaker has a past institution in a debate with an adjudicator who also shares a past institution with them. That said checking for this kind of test would probably involve changing the `Institution` data structure in a significant way which may not be worth the effort. 

A workaround could be adding a new form of conflict, say `TeamInstitutionConflict` that nominates that past institution which could then be checked against `AdjudicatorInstitutionConflict`.

**Comment by philipbelesky** [comment]
As a sidenote: there were apparently quite a few of these cases at Mexico WUDC

**Comment by philipbelesky** [comment]
@czlee sorry just noticed that you had explicitly added this to the current release. Is this something you wanted in before USUDC?

**Comment by czlee** [comment]
Um, it wasn't essential for USUDC (if it was I'd've put it on the USUDC milestone), I think it was just something I thought shouldn't be too hard. Don't mind bumping.

**Comment by philipbelesky** [comment]
Ah, I was thinking the front end implementation might be a bit tricky, although I could definitely give it a shot. If you want to make the changes to the model and hook it up to the conflicts/flags catcher on the admin draw page though I could have a crack at implementing it in the allocation page.

**Comment by czlee** [comment]
@philipbelesky I think I'd prefer the `TeamInstitutionConflict` model, since if we want to allow teams to have many institutions we still have to nominate one as the "primary" institution for things like team names. I'm possibly open to discussing having multiple institutional affiliations for teams and adjudicators if there's a good reason for it though. Did you have a preference here?

**Comment by philipbelesky** [comment]
Hmm, I think what I had though the problem with `TeamInstitutionConflict` was that rather than checking a conflict object against the property (i.e. institution) or someone else it then has to check against the presence of a second conflict object. 

But that said I guess the front end could parse `TeamInstitutionConflict`s on load and assign them as institutions which would then work with the standard adj-team institutional conflict checking mechanisms. So yea happy for that option and I think its a relatively niche use such that its probably not worth changing the more fundamental properties of how institutions work in general.

**Comment by czlee** [comment]
If it helps, when you think about it, checking against a `team.teaminstitutionconflict_set()` and against a `team.institutions` (being a `ManyToManyField`) are actually the same thing, at least under the cover 😉

**Comment by philipbelesky** [comment]
Yes, although I'm thinking about the front-ends implementation of conflict checking rather than the django methods. But I'm pretty confident they can adapt to whatever the new backend method is.

**Comment by czlee** [comment]
Cool. I realized (I guess this is what you were hinting at?) that we'd need to decide whether `TeamInstitutionConflicts` are automatically created and can be deleted, similarly to adjudicators, or whether `team.institution` is _always_ regarded as conflictable (alongside `team.teaminstitutionconflict_set()`). The former would require refactoring but would be simpler in the end.

I think they'd both be counterintuitive. The former would (in edge cases) require people to establish that the team institution conflict actually exists, in other words, there are _no_ conflicts which needn't be made explicit, which seems odd, because we normally think of team conflicts as automatic. The latter would mean that teams and adjudicators work differently. (For what it's worth, I think `team.institutions` would also be counterintuitive, in that your _former_ institution is not your institution.)

I lean towards the former, though, because for ordinary use we can auto-create like we do for adjudicators, and for edge cases it'd be easier to explain the concept to people when needed. Thoughts?

**Comment by philipbelesky** [comment]
Hmm, I think I'd rather it match the behaviour of adjudicators and be more explicit rather than having a magic behaviour for `team.institution`. That would probably also simplify the implementation in that you don't have to parse both attributes. Having them auto-create makes sense and would match the expected behaviour; the only risk is if people go poking around the Database and somehow remove this, which is probably pretty minimal.

**Comment by czlee** [comment]
Cool, sounds good!

**Comment by czlee** [comment]
Things to do:

- [x] Add models
- [x] Add to Edit Database area
- [ ] Add add/edit team-institution conflicts view to the import data area
- [x] Add automatic own-institution conflicts to command-line importers
- [ ] Add automatic own-institution conflicts to simple importers
- [x] Modify how the draw page computes what conflicts to display
- [ ] Modify adjudicator allocation algorithm to check team-institution conflicts and not own-institutions
- [ ] Modify how the adjudicator allocation UI computes what conflicts to display

Also conflicts are pretty messy now because they involve a gazillion loops, especially for checking team-institution conflicts against adjudicator-institution conflicts, so we should spend some time thinking about how to make this neat, and maintainable.

On a related note, I think we also don't currently check for adj-institution against adj-institution, when the institutions in question are not the adjudicator's own institution. This is a similar pattern to team-institution vs adj-institution, so I should probably just think through how to do this efficiently in general, really.

**Comment by czlee** [comment]
@philipbelesky It looked like no further work was required on the front-end, once the back-end dicts were in place! Is that right?

**Comment by philipbelesky** [comment]
They are in place for adj-adj past institution conflicts, but not for adj-team past institution conflicts as currently team conflicts are essentially hardcoded to read only from their current institution. I should be able to correct that though.
