### ISSUE TITLE
Add a method to credit a tournament's tab directors

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#573]
It's quite nice that tabbie2 relatively publicly credits the tab team, we should do the same. This could just be an input field on a Tournament preference; the trickier part would be figuring out when/where to show it. Misc thoughts:

- If we want people to actually use it, it would probably be best to include it during the create tournament step. 
- I'm not sure if we want to go as far as adding the org com / CAP also 
- As a default option it could show on the tournament welcome/index page as a list. It probably can't go in the header/footer of every page given how variable it is in size.

**Comment by czlee** [comment]
How about the adjudication core and organising committee, that too? Any reason people who want to do this can't just put it in the welcome message?

**Comment by philipbelesky** [comment]
I figure adjudication core are marked as such in the participants list; but I guess that might not be on. So happy to build it out to incorporate org com and adj core. 

The reason for not relying on it in the welcome message is that people don't really use it this way at present; presumably it feels like self promotion or aggrandisement to do so unprompted. If that capacity for recognition is instead built into the system and seems like an expected part of the process  it seems much more likely to be used. And at a meta-level I'd rather the system nudge tab directors towards being more visibly recognised for their work.

**Comment by czlee** [comment]
I see. I'd be fine with this. I think my thoughts match yours, except that I think all tournament officials should be listed. I presume this would be a free text field, right, maybe newline/comma-delimited so that we can change the presentation if we want? And I guess it'd show in a table on the right (like in Tabbie2) if the window's wide enough, or below if it's not?

I guess it'd have the neat side effect of our being more slightly more able to track down tab directors ourselves if we need to :joy:

If we add adj core, would we remove the boolean field of `Adjudicator`, since it's not (to my knowledge) used for anything other than presentation?

**Comment by philipbelesky** [comment]
I think the boolean field on `Adjudicator` (similar to the independent flag) has value when shown in context (i.e. with Institution; the hover over etc so I don't see a need to deprecate that.

At the moment my thinking would be separate input fields for org (com? team?) / adj core / tab team. A floating right-hand box would look weird when there is no other content on the tournament home page (i.e. all info is off) so will probably use a more horizontal arrangement of some kind.

**Comment by czlee** [comment]
I see. Are you worried at all about users not realizing that they have to set both independently? I guess alternatively we could just not have a field for the adj core and assemble names automatically from who's checked as `adj_core`, but then we'd have to nudge users harder to enter names of other tournament officials.

I normally refer to the organising committee heads as "convenors", and the org comm will presumably be too big to list completely. Annoyingly, terminology for this varies with circuit and there's not really any term I'd consider to be "more standard" than the others. ("Convening team"/"Organising committee"/"Convenors", "Adjudication core"/"Adjudication team"/"CA team", "Tab team"/"Tab directors".)

If we wanted to sacrifice common usage slightly for neutrality:

>**Tournament officials**
>- Organisation:
>- Tabulation:
>- Adjudication:

**Comment by philipbelesky** [comment]
The "tournament officials" with the bulleted list doesn't really work with the intended layout. That said I've adapted those as the headings for the tri-column layout, with a minor substitution of "tab" for "tabulation" (tab is much more recognisable given its slang use, particularly for ESL/EFL speakers). 

I've also stuck "team" on the end as it seems unclear what the purpose of each panel is if they don't clearly indicate that they are giving credit. I'm not super worried about there a single name potentially being labelled as a 'team' but would could explore a substitution.

**Comment by czlee** [comment]
Sorry for lack of clarity, that was meant to be a terminology suggestion, not a formatting suggestion (certainly not the bullet points part).

I'm not really sure what the link between the word "team" and giving credit is? Or if I interpret right, that it's not clear that these are names of people, in my mind this is what the more generic term "officials" (as in "tournament officials") was for.

**Comment by philipbelesky** [comment]
To follow back up on this — to my ear at least 'official's sounds a little too...official; or at least informal. 'Team' works equally well for small or big tournaments where the roles may not involve many people or be completely formalised such that the responsibilities are so 'official'.

'Official's is also less common in this context which makes it sound like a term of art. An 'adjudication team' or 'organisation team' seems to map to 'adj core' / 'org com' local equivalents where as 'official's might be over-extrapolated into being something like an observer / auditor / something specialised?

**Comment by czlee** [comment]
I don't have this connotation at all, other sports routinely talk about "officials" and it just means someone with a role in running the tournament, or running a particular game/match. I don't know if you intended for "official" and "informal" to be synonyms or antonyms, but I maintain that as a principle we should be using formal rather than vernacular terminology in software.

**Comment by philipbelesky** [comment]
Given how far debating is from real sports I'm not sure drawing analogies is definitely the way go :p. But even if doing so, an official in a sport is, to my mind, someone responsible for enforcing the rules of the games; not running it in a more holistic sense. I.E. a linesmen / umpire / referee. At a stretch maybe the CAP plays a similar role, but I don't think whomever runs the draws or does the events management for the NBA is ever referred to; much less as a official. 

I'm also not sure there is a formal/vernacular dichotomy; there can be informal vernacular and formal vernacular. In general I would say that we should preference formal language, but also preference vernacular language given that is what the people using the software are actually familiar with using in the context the software is being used. Introducing unusual terms seems like a violation of the don't make me think principle. Or if we are going to do so we should maybe just bite the bullet on choosing a preferred regional-dialect — i.e. any of the options out of "Convening team"/"Organising committee"/"Convenors" is going to be more understandable and stick out less than "Organising Officials".

**Comment by czlee** [comment]
I actually had "Organising Committee" in there for the precise reason that "Organising Officials" sounds unnatural, and also "Organising Committee" is a standard phrase used for events of every nature, including both sports tournaments and conferences. It's not a debate term. I found the asymmetry between org-comm and the other two mildly annoying, but I'll swallow it.

As If you're going for something that won't make anyone think, none of the standard terms for the adjudication staff and tabulation staff fall into that category, because there is no standard term. I only know what "CA team", "CAP", "A team", "adjudication core" and "adjudication team" because I've spent enough time talking to people from enough different circuits. I don't know whether "tabulation team" includes or excludes data entry volunteers.

The word that would make me think the least would a word that, in common (non-debate) parlance, implies some sort of authority. "Official" is one such word, but I concede that it's not perfect. If you're not a fan, I'm sure there are others. "Team" is most certainly not such a word.

**Comment by czlee** [comment]
Thinking about it more, I realized why I wasn't so sure about "Organising Committee": It's sometimes not a committee, but just one or two people; even where it is a committee, I'd imagine you'd typically use this field just to credit the 2-4 people in managerial roles (otherwise your list would be endless).

In fact, maybe the best method is just to have a rich-text field called "Tournament officials" or "Tournament staff" (or something similar) with the following text suggested as default, to nudge people about its intended use:

> **Organisation:** &lt;list organising committee members&gt;
> **Tabulation:** &lt;list tabulation directors&gt;
> **Adjudication:** &lt;list chief adjudicators&gt;

This breaks the column structure, but means that people can list exactly what they need/want. Part of my thinking is that people will inevitably ask to add language and equity officers to this list (there's value in making the latter easy to find), and while it might be tempting to keep adding fields, at some point I'd start to argue that it'll be easier to make it fully customisable (like break categories are).

The downside is that it wouldn't be enforceably standardised. In some ways, this is good: people could then use the terminology appropriate for their circuit. In other ways, less so: people might do weird formatting things (spaces before colons, lack of spaces after colons, inconsistency between single and double line spacing). We could counter this by enforcing a "heading, list of names" data structure. But I think that's too much effort.

I guess I also don't think this is just about crediting or recognising tournament staff. People want to, and should, know who's involved in running a tournament for all sorts of reasons.

**Comment by philipbelesky** [comment]
True, a rich text field is probably the only flexible option that scales from small to big relatively gracefully. A single-purpose field might get more use given its a more specific prompt but that's probably not worth worrying about. I've seen several tournaments use the welcome field like so already.

So I assume we just need to:

- [ ] Replace current multiple current fields with a new "Tournament Staff" rich-text field
- [ ] Provide a default value (or perhaps just an example in the help text to prevent accidentally adding the default when not using the wizard)
- [ ] Integrate that into the tournament wizard

**Comment by czlee** [comment]
Yeah. I think we might be able to do something clever to detect if the submitted text is the same as the default text, and blank it out if it is. (Model forms already do this, and in some context it's actually annoying.)

**Comment by czlee** [comment]
@philipbelesky close this after review if you're happy 🙂
