### ISSUE TITLE
Average speaker scores / margins not working

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#576]
Currently `da.speakerscorebyadj_set.all()` seems to return an empty queryset even when results are present.

Before fixing this though, @czlee is the performance hit of this relatively significant on page load times here? I can't really think of a circumstance where I've used it in a live tournament so it might be worth removing.

It might be worth fixing and keeping around in some fashion for if WADL ever gets brought up to latest, but in that case it should probably then be tied to one of their flags.

**Comment by philipbelesky** [comment]
Um don't have it in front of me, will follow up with precise lines. But the context here is the last cell shown on the feedback overview page. That cell is constructed in the feedback table class.

**Comment by czlee** [comment]
Oh, this is the feedback screen, that makes more sense—I was worried I had broken something in my recent standings refactoring 😛

Without having looked at it properly, in general, pages that only _read_ the database (as opposed to save things) _can_ be written to have not-too-significant effect on page load times, by using strategic prefetches. Constructing these prefetches can sometimes be complicated, but most of our problems with page load times are due to running hundreds of queries on pages that should only require a couple of dozen—not the SQL query itself or Python processing (unless we use more nested loops than necessary). There'll certainly be a performance hit, but if it's written right, it shouldn't be drastic.

But for what it's worth, I have no idea what the use case here would be, other than WADL. Wouldn't object to removing.
