### ISSUE TITLE
Speakers scores on team pages and debate ballots not redacted on public tab

### ISSUE THREAD

**Issue by Qantas94Heavy** [TabbycatDebate/tabbycat#577]
Even though speakers have requested to be redacted from the public tab, it appears this hasn't been extended to the ballot sheets for individual debates.

This can be seen on the Sydney Easters 2018 public tab for example: https://easters2018.herokuapp.com/easters2018/results/debate/36/scoresheets/

The **entire affirmative team** have redacted themselves (search up their names/team on the speaker tab) yet their individual scores still show up with their names.

This is perhaps understandable if only 1 person has redacted themselves (as they can be backtabbed anyway), but if 2/3 people have redacted themselves, we should also redact them elsewhere.

**Comment by viranweerasekera** [comment]
(This is just my two cents, feel free to disagree :) )

Not to say that a feature like this isn’t worth implementing, but I would suggest that allowing teams to do this would have other unintended consequences, particularly if it’s whole teams’ speakers redacting themselves from the public tab. Ballots are by nature relative; Speaker scores are awarded relative to the scores of the other speakers in the room, and at the point at which you remove the ability for speakers to compare their scores on a per-ballot basis, I would wonder if that impacts teams’ ability to meaningfully compare performance.

I’d also suggest that the driving force behind redaction is more likely to be an unwillingness to see how one ranks relative to everyone else, rather than just not wanting to know how they did (eg. In the Sydney Easters tab, 96% of the speakers that requested redaction also requested that their results be emailed to them, which would suggest that the problem lies more in the relative rank on the giant list that is a speaker tab).

**Comment by philipbelesky** [comment]
Hey thanks for opening this @Qantas94Heavy. The purpose and scope of the redacted feature that has been ambiguous since it was added and something that we are open to thinking about. As it stands we see its function as essentially masking a speaker's position within public rankings; that for whatever reason they do not want to be publicly identified in what can be construed on what is essentially a large list of who is better than whom. 

It is not, as currently imagined and implemented, intended to remove all evidence that said person was ever at the tournament — for example people's names still show on the public Participants page, on the Team record pages, and (as you've noted) in the per-debate results area. If someone wants to have all identifying details wiped from a tournament a tab director can go in and change that person's name in the database to be something like 'Redacted' or 'Anonymous', although I could see many tab directors differing on whether that is something they want to do. 

Given that option, the redacted feature provides an alternative to such a 'nuclear' option that preserves the record of person participating a tournament even if they don't wish to be publicly ranked. That said the record page is the only one of the exceptions I mention where scores are directly linked to particular persons scores so I could see the case for also redacting things there too, particularly if there many people have a problem with it. Is reporting this from Easters prompted by some people wanting to be redacted from ballots, or is this raised as a more hypothetical concern or FYI bug report. Anyway I'll have a think about this; @czlee might also have thoughts.

**Comment by czlee** [comment]
My thoughts are broadly the same as those of @viranweerasekera and @philipbelesky. The only thing I'd add is to point out that there are lots of different permutations for precisely what "redacted" might mean, and supporting all of them would require a lot of special-case code.

**Comment by tienne-B** [comment]
Should this task be closed as it is WONTFIX?

**Comment by czlee** [comment]
Yeah. I'd be happy to reconsider on the other side of WUDC (_i.e._, in 2019) if someone wants to make a case for it, accounting for our thoughts above.
