### ISSUE TITLE
Investigate second-tier of public page caching

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#658]
While 1 minute is a pretty good conservative estimate for pages that publish new information or represent often-modified data, there are a class of pages that update less frequently — i.e. they only typically update on a round by round basis — and could benefit from a large timeout period (say 10 minutes?). In decreasing order of confidence:

- [X] Participants
- [X] Diversity (oops — already cached at the tab settings)
- [X] Institutions list
- Results
- Breaks
- Standings
- Feedback Progress

**Comment by philipbelesky** [comment]
@czlee Did you have thoughts on the this proposed change? I'm wondering whether query caching or async cache generation would offset the need for them, although it seems like a relatively harmless change* — I was thinking maybe a 5-10 minute timeout for these pages.

*The only pages that I think would be problematic with a longer timeouts is the feedback progress page, as I think users want to be able to do what is due then check for updates to verify that their feedback has been recorded. That being said the existing 1-minute cache probably has a similar issues, so we could perhaps add a 'this page is up to X minutes old' perhaps along with a 'check your records page for faster info' note.

**Comment by czlee** [comment]
For the first four items (participants, diversity, institutions list, side allocations) I don't have a problem with this. For results and standings I feel like they're also pages where people want to check things as soon as they can, so would be hesitant about lengthening those.

How confident are we that this is the root of the problem, though?

**Comment by philipbelesky** [comment]
Results and standings essentially only update once a round though; i.e. they only show after the round is advanced. From a user's perspective when a round will advance is essentially unknowable and abritrary so I don't think it's a problem for them to have a <10 minute delay — it just changes when 'as soon as they can' is. We could also note this in the round advance screen so that tab directors are aware of it.

I'm somewhat confident that degraded performance comes from the having a few relatively expensive views which then exacebate a cache stampede effect. This should tackle the latter half of that problem.

**Comment by czlee** [comment]
I still think ten minutes (or seven-and-a-half) is a long time. At least, I like to _think_ it's a long time in the context of in between rounds. I could do like up to 4 minutes for results and standings?

Also, those views only take a few seconds to generate each, even locally with debug toolbar enabled. They're not _that_ expensive intrinsically, though of course they are if we have multiple requests per second. Is the "stampede" effect you're referring to the phenomenon where, just after a cache is expired, all requests to the page trigger the view code until the first completes, which could be many at the same time? If so, shouldn't there be a remedy whereby we can regenerated cached pages before expiry, so that the old cached version continued to be served before the updated version is complete? We can't be the first people to have had this problem?

**Comment by czlee** [comment]
Ah, I see you've covered the latter in #663. Nvm with that discussion/continue it there then.

**Comment by philipbelesky** [comment]
Ok, cool. I've extended to results/standings while lowering the slow
timeout to 3.5 minutes. Will hold off on further changes until some sort of
load testing is setup so we can evaluate the async/query  caching options
and see what their effects are.
