### ISSUE TITLE
Participant check-in could be done by the individuals

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#684]
This may also be a contentious feature, but having participants check themselves in could be added. With the live views of check-ins (even with the "assistant" view which is also for display), instructions for self-check-ins could be shown, with officials overriding and complementing this self-system. Of course there would be settings to enable this feature.

There are two methods I thought of for it:
* **Inbound email**: Participants will be requested to send a message (say `!checkin`) to the sendgrid email address (which does take inbound messages). Then, the linked participant to the email gets their status updated live (or with a reply). Un-linked addresses could get a reply indicating its failure.
* **Private URLs**: A page for each participant/team with a simple "Check-in" button is created using their related private URLs. Pressing it updates (toggles?) their status.

Both these methods would take the timeframe into account for rejections.

**Comment by philipbelesky** [comment]
Hi @tienne-B. I think the 'private URL' method would be most fitting with how user interaction is handled across Tabbycat. Inbound email sounds interesting although ideally it would be nice if features were not overly attached to specific addon providers like sendgrid.

One note for the private URLs thing, I'm not sure if a POST request can be issued from an email (or if so it might be blocked for cross site scripting reasons). But that could probably be avoided by having the check-in private URL just be a page with a check-in button that then POSTs. As a side benefit that page could probably confirm if a user has been checked in (and when) and potentially allow them the ability to revoke a check-in if you think that would be useful.

**Comment by tienne-B** [comment]
No, `POST` requests cannot be done through email. That is why the link would have a "confirm" button, in addition to specifying the applicable timeframe.

Should individual debaters have their own URL key (being aligned with the current framework)? Then, the key could be associated with the `participants` model; not in the `adjudicator` subclass. This would potentially be a separate issue, but there could be a merging of the checkin IDs with the URL IDs (switching to alphanumeric barcodes). However, there could be concerns about data security; exposing the participants' "private key"s at the registration desk. Thoughts?

**Comment by philipbelesky** [comment]
Hmm, I think using a URL key in a similar fashion to what we do for eballots/efeedback would be best. Part of the reason we chose just numeric rather than alphanumeric barcodes is that this speeds manual entry, particularly on mobile devices, so it would be great not to need to compromise this. And while unlikely, it would probably be relatively easy (if desired) to check in other people as their barcode is currently shown to the public in the UI (and on the barcode itself often)

**Comment by tienne-B** [comment]
So keep the private alphanumeric ID and the public numeric ID separate. As with other private URLs, they use the `Submission` class as the base model. This adds fields for the method inputted and the actor, which would now be applicable for the `Event` table. Should `Submission` be split into something like `LightSubmission` for a new use in `Event` to maintain this information in all uses of these URLs?

About security, I took the more cynical view that not only participants could check-in each other, but with the knowledge of the keys submit false ballots. 😬

The plan is:
* [ ] Add ability for adjudicators to check-in/out through a private URL
  * [ ] Split `Submission` class and make the `Event` table a subclass of it to record more information about the actor of said action.
* [ ] Add ability for **speakers** *(Inferring Teams)* to check-in/out through the same means
  * [ ] Move private URL key from `adjudicator` table to `participants` table (and thus give individual speakers a key)
* [ ] Send email to the participants informing them of the URL.
  * [ ] Should it reset after each check-in cycle?

This is a big plan, and each point seems to make some big change. How does this plan sound?

**Comment by philipbelesky** [comment]
>  Split Submission class and make the Event table a subclass of it to record more information about the actor of said action.

This I am a little wary of given that the primary use case for Check-Ins is based on an event-stream like model where pages send and update data live over web sockets, rather than by using `POST` mechanisms. Although that said having more information about those check-in events wouldn't be a bad thing by any means, but we would probably want to prioritise the performance and function of the existing mechanism and make sure any changes play nicely with the the `checkins/consumer.py`. Could you clarify what you mean by splitting `Submission`?

>  Add ability for speakers (Inferring Teams) to check-in/out through the same means +  Move private URL key from adjudicator table to participants table (and thus give individual speakers a key)

Sounds good; although I think at that point maybe we should remove `url_key` from `Team` and then rely just on the participants key when doing feedback. That could also have the side benefit of enabling feedback submissions to note the source in a more granular way, although would require refactors to those forms I think.

>  Send email to the participants informing them of the URL

It would be best if this mirror the other private URLs; i.e. designed to be sent once. I guess if people want to send it repeatedly they can just trigger that action manually as needed?

On a relate note, given we now have essentially three different private URLs sharing the same key, would it be worth just consolidating those methods into a single page? So rather than have seperate URLs for ballots/feedback/check-ins, there is just a single landing page that then offers users whichever actions have been enabled for their account? That would make bookmarking (and emailing) much more simple @czlee?

**Comment by tienne-B** [comment]
By splitting `Submission`, I mean having `timestamp`, `submitter_type`, `submitter`, and `ip_address` as the `Submission` class, then having the other (`version` and confirmation) fields as a subclass `ConfirmedSubmission` which would be used for the current uses of `Submission`. However I understand the need to keep the `Event` table lean, and adding this kind of info may not be as useful, especially as the rows are regularily deleted. With that, the `Event` table should not be expanded.

The implications of using just the participants' keys are interesting as you show. It could also pave the way for the debaters to submit feedback individually (however I suppose per team is preferred?)

Would it be okay to denormalize the schema a bit more by also making `Tournament` a field of `Person`? Then I think I could use `tournament.person_set`. This is where I'm stuck right now.

**Comment by philipbelesky** [comment]
Hmm, I'd be pretty wary of shifting `Tournament` in that way given there are some pretty deep assumptions about the relationship between teams/adjs and tournament. There are also some complicated use cases — we would need to maintain `Tournament` on teams also, so having it be inherited present on `Speaker` seems like it could get confusing. If the problem is just the query though can you do that by extending through to `Person` based on the `team_set` and `adjudicator_set`? 

I personally would not have a problem with adding those fields to `Event`. At our scale having more fields probably isn't really an issue in terms of database speed I think. If anything I suspect the performance impact of having an abstract model might be worse? But regardless of those concerns I'd also be wary of tinkering with `Submission` if we can avoid it, given how deeply it is tied to core functionality in terms of results.

**Comment by tienne-B** [comment]
Yeah, I'm trying with queries like `Person.objects.filter(adjudicator__tournament=tournament, url_key__isnull=False).exists() | Person.objects.filter(speaker__team__tournament=tournament, url_key__isnull=False).exists()` but those are quite ugly. By denormalizing the DB, I did mean just add the `Tournament` field to `Person`, not removing it from `Team`.

I'm trying that now, and would require a little change from `.adjudicator_set` to `Adjudicator.filter()`, as is done for speakers.

I'm having second thoughts about using `Submission`-type fields in the `Event` table as the objects in that table are regularily deleted without logs, and so having this type of information present would be kinda useless (perhaps just a "submission-type" so that participant events could be reviewed, but even then...)

**Comment by czlee** [comment]
Hey, so I just had a look at #690, thanks for all your hard work here.

**Database schema—tournament field.** I can see why moving `tournament` to `Person` makes some queries easier, but I'm not really a fan of it. I try to make models reflect what they _actually_ describe, rather than risk situations where a team can have two speakers that aren't in the same tournament as it. If a particular query is clumsy, I'd rather encapsulate it in a function and make use of that function. I've dealt with a few complex queries before (sometimes going down to raw SQL), so let me know if there's a particular query you can't construct and I'll be happy to help. I'd prefer an ugly query to a confusing model structure.

(I know I've been slow, sorry. If my lack of response is blocking you, ping me by email and I'll bump it up my priority list.)

**Database schema—URL key field.** I think moving `url_key` to person is a good move. It has other benefits too—it means we can track precisely whose URL was used to submit a form (feedback), in case there's a dispute we need to resolve later.

**Database schema—Submission field.** I actually think we're on the right track, but as you've discovered there's a pretty fundamental rethink we need to do here. At the risk of going too abstract, the question that would help us decide on this is, "_What is this model for?_" `Submission` was originally just intended to capture common functionality that you'd typically record in ballots and feedback, like you say. I have to admit, this purpose wasn't very well-defined, but in particular, it's _not_ a logging function. (That's why, for example, it has automatic versioning.)

I feel like we're now talking about a different purpose (logging), but one that was originally conflated with "submissions" because at the time it _did_ make sense to conflate them.

Here are a few complicating factors:

- With all the functionality we're adding, a "URL key" is really turning into an "account" of sorts. You could argue that what we're really angling towards is a history of actions performed by that "user". That's actually sort of closer to `ActionLogEntry` than `Submission`. (Related: #683)

  (Just to complicate things a bit more: it's long been a wish of mine to reform the `actionlog` to be more like an [activity stream](http://activitystrea.ms/), using something like [django-activity-stream](https://github.com/justquick/django-activity-stream), though I was in two minds about whether it would be worth it. See: #229)

- Either we need to deprecate the public ballot/feedback submission functionality (where you just click on your name from a public list, _i.e._ no security whatsoever), or we need to make sure our current migration is compatible with it.

- `Submission` is currently set up to handle both actions by authenticated users, or IP addresses, mainly just to keep a paper trail about where something came from. In our new system, are "URL key users" and authenticated users just "different types of users"? Do we insert an abstraction layer here? Or is there some fundamental distinction in how we log their actions?

**Consolidation into a single landing page.** With respect to this:

>On a relate note, given we now have essentially three different private URLs sharing the same key, would it be worth just consolidating those methods into a single page? So rather than have seperate URLs for ballots/feedback/check-ins, there is just a single landing page that then offers users whichever actions have been enabled for their account? That would make bookmarking (and emailing) much more simple?

Yes, I agree. This would basically extend the private URL into an account-like thing, as discussed above. Except that it's not an account, because we don't really trust participants to set them up properly for each tournament.

**Security.** For what it's worth, I'm not _so_ fussed about people seeing URL keys at registration desks. They're pretty hard to memorize from a quick glance, and URL keys are meant to be a simple disincentive against the _temptation_ to abuse identities, not robust protection against determined attack (if they are, they're terrible for the job).

But I _would_ be concerned if URL keys were printed on lanyards, since they're the kind of thing that people tend to leave lying around. So separating them from check-in barcodes was a good idea. 😃

**Comment by tienne-B** [comment]
*Schema-Tournament*: I've made the equivalent to `person_set` a property of `Tournament` (as `.participants`) using `Q`. Neat thing. With that, all the queries are done.

*Schema-Person*: This goes to the re-thinking of `Submission` with logging the actor by individual and not by group. The current PR does not address this for `adjfeedback`.

*Schema-Submission*: You're right for the split purposes that `Submission` has gained.

The URL key is becoming some kind of account, and it could be an idea to extend the log to all participants' actions. An idea would be to "connect" `auth.user` with `participants.person` (maybe `Staff(Person)` with a OneToOne field towards `user`). There isn't (or shouldn't be) a fundamental difference in how these actions are logged.

I'd deprecate the public forms, and with that remove the `ip_address` logging as everyone would have a `Person` record associated.

**Comment by czlee** [comment]
I'm guessing we decided to leave the `Submission` and `Event` models as they are now, and punt any further reconsideration of this to a new issue? (I'm fine with this, and don't even think it's urgent, just checking we're on the same page.)

**Comment by czlee** [comment]
It should be possible to write `make_feedback_form_class()` so that it still accepts a `Team`, right? When it accepts a `Speaker`, it just looks up its team and passes that on to `make_feedback_form_class_for_team()` anyway.

**Comment by tienne-B** [comment]
In my view, this would be a reason to ditch public submission forms.

What about asking the participant to select themselves, instead of their team. Then we'd get the "correct" (unverifiable) speaker for the log but the correct team view. However the list could become >2 as long. (Feel like this thread should be broken up a bit...)
