### ISSUE TITLE
Team tab's results cell loses information on copy/paste or print

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#7]
Either do this in HTML or maybe generate PDFs using ReportLab http://www.reportlab.com/software/opensource/

**Comment by czlee** [comment]
Are the tabs still printable? It's just occurred to me that the enhancements you did when we overhauled tables (to add tooltips and save space) might have broken easy copy-paste.

**Comment by philipbelesky** [comment]
Seems so? Using `CTR-P` and save to PDF or printing directly to a printer works. As does copying to Excel.

**Comment by czlee** [comment]
Oh I mean, you can print it, but like do we want to make it more amenable to a printable format? For example, the Australs 2016 team tab leaves the first page mostly blank, so that the table can begin on a blank page. Also, copying to Excel doesn't copy the win/loss arrows.

**Comment by philipbelesky** [comment]
The blank page thing was fixed in f71d63e2e492d180184790048b991aa0e3899ca8. The problems with copy/pasting and the results cells are much harder:

- [] Having the opponent emoji copy over to Excel is questionable; it isn't hoverable such that it no longer really reveals who the team was
- [] The glyphicon doesn't copy over full stop

In both cases there doesn't appear to be any attribute or CSS hack that allows us to specify a kind of 'alt' text for copy paste that the browser copies over instead of the icons/nothing. The only way around this I can think of is having a button called like "copy paste view" that uses JS to swap out the icons/emoji for full text in order to be copy/pasted. Using JS you could also intercept a CTRL-C keyboard shortcut and perhaps do the clipboard substitution there but it would be a royal pain to selectively figure out what needs to be substituted.

If we only cared about copying over the arrows we could substitute the glyphicons with a [unicode arrow of some kind](http://xahlee.info/comp/unicode_arrows.html) but (for now) at least I'm willing to accept that the team tab doesn't copy/paste (or print for that matter) well. As long as the speaker tab does :p

**Comment by czlee** [comment]
Another option would be just to have a very plain (well, plain text, so icon/emoji-less) version in a separate view. What would your take be on that?

It'd be annoying to keep in sync with the proper version, but because it's plain text it should be easier to generate.

**Comment by philipbelesky** [comment]
I don't think it's worth maintaining a separate view just for the team tab and copy/paste purposes. 

If the major problem are the win/loss indicators I think we should use a unicode arrow substitution but even that probably requires a rework to `Cell.vue` or some some sort of CSS psuedo-element to swap it in for the normal glyphicon.

**Comment by philipbelesky** [comment]
Closing this as copy/paste seems to work fine on recent tabs and whatever small differences exist I can't be bothered fixing.

**Comment by czlee** [comment]
tbh, the CSV API should be what provides this functionality
