### ISSUE TITLE
Include average speaks in speaker standings/tab

### ISSUE THREAD

**Issue by nzervoudis** [TabbycatDebate/tabbycat#733]
Most people are quite bad at dividing large numbers by 4, 5, 9 etc. 

It would be useful if alongside (and probably on the left of all other scores), speaker tabs included a speaker's average.

**Comment by czlee** [comment]
This feature is actually already there—it's just an optional setting that tab directors can enable or disable, under the "Standings" group of the tournament configuration. (see: [options/preferences.py:543-575](https://github.com/TabbycatDebate/tabbycat/blob/v2.1.2/tabbycat/options/preferences.py#L543-L575))

But the default for BP is `['total']` in precedence because the WUDC constitution says to rank by total, and `['stdev']` in extra metrics (metrics that aren't used for ranking). So maybe we could just add `'average'` to extra metrics?

**Comment by tienne-B** [comment]
So should `average` be placed in presets for speaker tabs? Or should this issue be closed (without action for #736) I took the task to be about team tabs because `average` already existed for speakers. Still think this "average of averages" for team tabs would be useful (for the reason @nzervoudis brings forth) though.

**Comment by philipbelesky** [comment]
Yea, I think this was something that was overlooked in terms of adding BP support. Within Australs format the average is used for rankings so is always present. In BP its not used for rankings but is nice to have (more so than standard deviation lol). Will discuss this 'average speaker average' separately in #736.
