### ISSUE TITLE
Individual scores should be deconstructible

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#771]
There are formats where individual scores are broken down into criteria (for the Canadian National Debating Championships [high school]: Content, Style, and Strategy) _Personally, I dislike having these codified criteria, and think they are contradictory to their instruction to judge "holistically."_ These criteria can have different scoring ranges, but are summed to form the speaker's speech score.

Tabbycat should be able to include these criteria in ballots, possibly being akin to adjudicator feedback questions. This would make Tabbycat more flexible for other formats and be able to hold more granular data, which is often ignored or not included in the tab.

**Comment by tienne-B** [comment]
I dislike the idea of just having these three criteria as fields as it would inhibit customization. I think this should mirror somewhat the models for adding adjudicator feedback questions. There could be a table like `SpeakerCriterionScore`:

field | type
-----|-----
_id_ | Primary key Integer
`criterion` | Foreign key to a `score-criterion` table (or something)
`score` | Decimal
`speaker` | Foreign key to `SpeakerScore`

There are formats that have different criteria (sometimes more), like (1) Organization (2) Evidence/Logic (3) Presentation (4) Refutation (5) Format.

**Comment by philipbelesky** [comment]
Ah right, if there are formats that use more than those standard criterion that would make sense. I think we would still want the preset/configuration options to somehow provide the 'standard set of criterion' if this is to be an expected feature of running a WSDC style tournament. That is to say in toggling the relevant preference (or applying the relevant preset) the standard trio should show up as expected — perhaps via a hook in the `validate()` method of that preference. Ideally needing to access the database area should be an exception to running a standard tournament rather than something necessary to do so.

**Comment by czlee** [comment]
I concur with the model in @tienne-B's comment above. (I also personally agree that this deconstruction is silly, but I'm sure that's just a reflection of the circuits I've spent the most time in.)

It's not really clear to me what the "standard trio" is though. In my high school league (a long time ago!) it was just "matter" and "manner". WSDC doesn't currently use Tabbycat; if they're going to get primacy, I'd want a good reason for it. In any case, setting up "standard configurations" are what we have presets for.

Because this complicates the code base, I'd want to know that a tournament will actually use it before anyone implements it.

**Comment by czlee** [comment]
Yeah, something like that. It's not obvious to me exactly how we'd implement it, but it'd be good if it were somehow conceptually part of "preferences", at least from the user's perspective. If we manage to come up with a good pattern for this, it might also work for feedback questions (which we currently auto-populate when a tournament is created using the GUI).

**Comment by tienne-B** [comment]
I've thought of the task a bit more.

`ScoreCriterion` table:

field | type
---- | ----
_id_ | Primary key INT
`tournament` | foreign key to `tournaments_tournament`
`name` | `CharField` not blank
`seq` | Integer
`weight` | Integer/Dec? _default: 1(.0)_
`min_score` | Decimal
`max_score` | Decimal
`increment` | Decimal
`required` | Boolean _default: `TRUE`_

Different criteria could be weighted differently, or with a different range/allowed increment and so it should allow for a wide flexibility.

This table would have significance even without the use of "criteria." Both reply scores and constructive scores could be counted as being criteria. As not every speaker would have a reply score, it would be non-required, but constructive scores would be. The difficulty would be to identify if it is a constructive/reply criterion (although I guess a Boolean field could be used).

I don't have much of a pattern for it, but the "going further" part would have lots of scoring rules options removed in favour of criteria. The area of "Set current round" could be used to link to formsets to add feedback questions / score criteria.

**Comment by czlee** [comment]
Hmm, in formats that score reply speeches, they're not really analogous to content/style/strategy divisions. They're just different speeches altogether. More generally, I'd be wary about instituting a system that complicates (even internally) what is currently the standard use case (not having criteria). That is, I think that the `ScoreCriterion` and `ScoreCriterionScore` tables should both be left blank in formats that don't divide speaker scores into WSDC-like categories, just as `SpeakerScoreByAdj` is currently left blank in formats that use consensus ballots (as opposed to voting ballots).

Other than that: I think that schema is sensible. We normally call the increment "step" in this context (both words are equally acceptable, the latter is just what's currently used in analogous fields elsewhere).  

Question: Would I be right in guessing that the `weight` field just controls the coefficients when combining them, so for WSDC where you just sum the components, you'd set them all to 1.0, but if you wanted to (say) average four criteria rather than sum them, you'd set them all to 0.25?
