### ISSUE TITLE
Adjudicator pop-ups get clipped if its height is bigger than the draw table

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#774]
In the draw table, if there are many adjudicators for a debate and few debates, the pop-up of judges and their record links gets clipped by the top of the table.

A thing that could be done is to remove the separate "Record of ..." line, just having their name link to their page, as that seems like the only page that relates to the adjudicator.

**Comment by philipbelesky** [comment]
Hey, this is definitely a known issue. It also one of many issues in the way in which those popups work at present — they are kind of an unholy mashup of jquery/bootstrap functionality called within Vue so as a result they don't get dereferenced properly and have little knowledge of the overall table geometry. Fixing that would involve property implementing `popper.js` functionality within the Vue tables themselves or perhaps going all-in on a library like [bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue) that removes the need to use bootstrap's js modules directly. 

That is a pretty big project that was abandoned (for now) in #297 but perhaps could be revisited in the long term — we could probably get to the point where jquery is a drop-in rather than global dependency but doing so involves reworking a lot of common functionality like icons, tooltips, modals, etc.

**Comment by tienne-B** [comment]
What about the stopgap that I proposed? Linking by name is done on the adj record pages.

**Comment by philipbelesky** [comment]
Ha, no problem opening new tasks — its good to have limitations/problems noted down rather than just implicitly known. 

For the stop gap I'll need to check the code to see if anything else shows up there that necessitated that structure. But we could definitely combine the "Name + institution" line with the "Record link" line which should reduce the vertical space. It's probably still necessary to name the record link as such — people broadly don't know what these are. But we could just say "View Record" in the interest of economy.

**Comment by philipbelesky** [comment]
Hmm actually having tried this collapsing the two into a single string doesn't actually help as that string always wraps over two lines anyway. And in doing so it means the link is not aligned/placed consistency and so is harder to read/access.

**Comment by tienne-B** [comment]
I'd just link the name in the pop-up as is done on team/adjudicator record pages. I couldn't think of what other target such a link would have other than the particular's record. I advocate for ditching the "View record" text entirely as linking the name would be just as understandable. I don't see naming the link would actually help with introducing people to record pages.

**Comment by philipbelesky** [comment]
Closing this as this was partially resolved in above commits. Feel free to re-open and re-assign if a more complete solution is desired.
