### ISSUE TITLE
Change ballots graph to a more appropriate chart-type

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#776]
Originally reported in https://github.com/TabbycatDebate/tabbycat/issues/392#issuecomment-414520858, but it seems to be a different task. To re-state, the graph found in the admin's overview page should be a line chart for clarity. The changes in the lines for different statuses (unreceived, checked-in, unconfirmed, confirmed) and the times these statuses change is more easily seen and compared (with the intersection of series) through lines.

> @philipbelesky: Isn't that the function that the ballots status graph provides on the tournament dashboard/home page? (https://github.com/TabbycatDebate/tabbycat/issues/392#issuecomment-414566930)

No, the chart currently being used is a bar chart, which is a chart-type for discrete groupings (which time is not). As such, bars aren't ideal for this use.

**Comment by philipbelesky** [comment]
I'm not sure people who use the graph are more interested in the time that those statuses change than the actual proportion of statuses in each category. The graph is always up to date and intends to answer the critical question of *how many more ballots are there to go right now?* while the general shape of the previous results given an idea of how quickly each type is decreasing or increasing. I'm not sure the exact times matter much. 

But definitely open to the idea — having a properly spaced time axis along the x might make it easier to construct the graph and presuming it clearly displays the proportion of status would provide the benefit of more accurately showing the overall time periods.

**Comment by czlee** [comment]
For what it's worth, we used to have an area chart with a correctly spaced time axis there: https://github.com/TabbycatDebate/tabbycat/blob/77a078ebe962b558d80eb76a8ec2606f3e9a4b8b/tabbycat/templates/graphs/BallotsGraph.vue#L52-L103

We reverted it to a stacked bar chart in b98f0fe6743b475116543fdbaa2a09d3712781af:
https://github.com/TabbycatDebate/tabbycat/blob/b98f0fe6743b475116543fdbaa2a09d3712781af/tabbycat/templates/graphs/BallotsGraph.vue#L52-L127

My understanding was that this was due to a d3 package upgrade, and that we always intended to revert it back to the area chart with a correctly spaced time axis, just with low priority. @philipbelesky, was I mistaken?

Personally I'm definitely interested in understanding the time that those statuses change, which is why I had changed it to an area chart with correctly spaced times in the first place. I want to understand whether our delay is due to a handful of very slow ballots, or whether the ballot progression is roughly even at a slow rate.

**Comment by czlee** [comment]
Something of this shape is closer to my preference (I dug this image up from screenshot archives), but with time-axis labels that are more useful than the gibberish in this image:

![example](https://user-images.githubusercontent.com/1725499/44422636-9157c480-a538-11e8-9062-ea16b56f0b56.png)

To understand the current proportion of ballots in each status, you just look at the right-hand side of the graph, as we do currently.

I also thought it'd be nice to have historical graphs available somewhere, _i.e._, for previous rounds (on a different page), to improve our understanding of tab room operations.

I don't really regard this as _that_ low priority, just lower priority than everything else we have on our plate right now with preparing for the upcoming WUDC prep season.

**Comment by tienne-B** [comment]
Should ballots that are checked-in (but not draft/confirmed) have a colour (grey?) Also, as they are SVG, maybe they could be resizable (although I guess not as the axes would have to be recalculated).

Other tickets for those points?

**Comment by philipbelesky** [comment]
Yea check-in status would be nice to show. It's maybe a little tricky in that its distinct to the actual status, but given you only care about non-checked in ballots they are also likely to have a status of none. So that red bar could be split.

I'm reworking the way new ballot statuses are broadcast as part of #433 which will probably involve reworking how this graph is constructed. I may or may not have time to also rework it back to be an area chart then too.

**Comment by tienne-B** [comment]
I'll try to make it an area chart. I'll wait for #433.

**Comment by tienne-B** [comment]
Closed with 68c2e30e5a4999d1fe85b79ed355b024fc123beb.
