### ISSUE TITLE
Email draw notifications: enhance un/re-release handling

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#790]
Currently the email system has no awareness of draw re-releasing or un-releasing. Participants probably should be notified of these events, or perhaps a delta run on the previous draw and participants only with updated matchups notified.

**Comment by tienne-B** [comment]
By doing filters based on context JSON, delta runs are possible. If we go that direction, only the venue and match-up parameters should be taken into account. Should the members of the panel also be taken into account? That could be important, but would pose some more difficulties. Don't care much if the positions of adjudicators change however.

In either case, whether we do a delta run or re-send to everyone, there should be a message stating that it is for the re-released round to avoid confusion.

**Comment by czlee** [comment]
I like the delta run idea. I think there's a case both for and against notifying about judge changes (for: it's a change some will care about, against: it's already common to change judges once prep has started because of unknown conflicts).

I'd caution about notifying on every unrelease or rerelease though. An unrelease might be an accident (and the rerelease then fixes the accident), or it might be just to rerun adjudicator allocations (to prevent accidents, we prohibit auto-allocating adjudicators if the draw is released). The exact workflow isn't obvious to me, but I feel like in such situations the tab director should have some sort of real-time control over what emails get sent.

**Comment by tienne-B** [comment]
I wasn't thinking of notifying on un-release because the changes done during the time it is un-released would not necessarily affect the participants. I was wondering about judge changes as replies to the emails could possibly indicate previously unknown conflicts, and so it is best to update based on those changes.

As a solution to more control over sending emails, there could be a different button to (re-)send emails. Going away from specifically notifications, there could be a message showing which adjudicators/teams have been affected between releases as a summary. Think that would be useful?

**Comment by tienne-B** [comment]
Showing the difference in who will be sent messages would be simpler than showing the specific change(s) affecting them.

**Comment by tienne-B** [comment]
Close this as moot (with #879)? Emails aren't automatically sent, and specific people can be selected for an amended message (with a custom notice). Follows the `printing` pattern.

**Comment by philipbelesky** [comment]
Yup, think this has been superceeded

**Comment by czlee** [comment]
Actually—I haven't been keeping up, so apologies if this is a dumb question—does #879 provide a way of easily identifying the delta we discussed above? As in, say a tab director wants to send the new notification to just those who have changed—do they have to know in their head who has changed, or can Tabbycat auto-select them somehow?

**Comment by tienne-B** [comment]
No, it doesn't. They have to know in their heads. I have previously shown why determining the delta is harder than expected. It would basically have to run the email generator before confirming to send and compare the context dictionary. (Would break the pattern I established)

This is also a problem in the status-quo for printing ballots though; the difference here was that emails were automatic and so if released many times, could cause confusion. Now that they aren't as they are sent through a different button, the issue is moot.

**Comment by czlee** [comment]
Of course—it doesn't surprise me that it's highly nontrivial, but I don't think this makes the issue so much moot, as it is less critical and different in nature. 🙂 Maybe the issue of "auto-selecting just those adjs with changed assignments" should be a distinct and new issue, though.
