### ISSUE TITLE
Rethink UX of feedback form to prevent unnecessary submissions

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#812]
The problem of people submitting feedback on panellist rather than the adjudication-deliverer seems to be relatively endemic. I added a warning to the form in fa70381d930b9628ec8bb62c2a85ad3faeb7e89e but I suspect this is not going to be enough.

I suspect a more robust method would be to structure the questions in the form to properly limit choices based on what happened in the debate. My first thoughts for that structure would be:

1. Which round is this for? 
    - *This then filters (3) based on the answer*
2. Did the chair deliver the adjudication?
    - *This then filters (3) to either be a disabled/single-option `select` or a multi-option `select`*
3. Normal adjudicator selection drop down

The intermediary step of (2) would only show if the relevant `feedback_from_teams` pref matches. It is probably also worth adding a `help_text` or similar that reiterates the expectation of the setting (i.e. a slightly more subtle of the alert added in fa70381d930b9628ec8bb62c2a85ad3faeb7e89e).

If it makes the implementation easier I wouldn't mind if these three questions were actually presented prior to the standard form being shown; i.e. as a two-part formset or as separate forms. Having them as separate pages might also further reinforce that it is a task that doesn't need to be repeated for every available option.

Finally, in the 'nice to have' bucket, I wonder if its worth having some way for teams/adjs to see what feedback they have already submitted. This could help the case where different members of the team accidentally submit duplicate feedback not knowing someone else had done so. We could potentially roll the team record links into the private URLs for this purpose or do something more limited.

**Comment by czlee** [comment]
For what it's worth, I think this is enough work to qualify as "outside the scope of Tabbycat" and "should be delegated to a third-party system". Alternatively, if we're giving up on the idea that someone else might develop a meaningful adjudicator feedback system, our overhaul wishlist also includes other things of possibly higher priority. Most notably, we often get requests to differentiate between feedback on chairs and feedback on panellists, which I've been resisting because it would entail a structural rework of the feedback forms.

I don't think anything's going to be really enough to satisfy us in terms of user experience and guidance, short of a structural rethink of how feedback submission works. Although we've added lots of bells and whistles, the current system's architecture is still mostly based on the Australs 2010 system, when data entry was limited to tab assistants and we didn't need to foolproof the system from debaters. The only appreciable structural change since then was in 2014, when we added the submission version numbering system to support public submissions for the first time.

**Comment by philipbelesky** [comment]
While the workload involved might put this outside our scope sufficient to include in a third party system, I don't think this change (or rather the underpinning problem #813) is outside of the scope.

Firstly in that we've gotten a lot of feedback, particularly at large touranments, that this is a problem with the existing feedback system as-is. This to my mind is a relatively clear problem with the *current* mechanisms of the feedback system rather than the standard set of enhancement/features requests for a more flexible feedback system that would be better served by a third party. 

Maybe I'm missing some things but it also seems like a higher priority than other items on the wishlist. First because of the reports mentioned above, but also because of the actual side effects of not preventing the problem this issue aims to address, which is that adjs who did not *give* feedback end up receiving scores as if they had. These scores are essentially bad data, and require a lot of work on behalf of the tab director to identify and remove. 

On the workload front I wasn't thinking that this would require any structural changes to the models or mechanisms of how the forms record data. An ideal implementation would require altering the mechanics of the django form that is presented to users, which I know can be difficult. Alternately, a good-enough implementation could use some simple JS on the page itself to filter and present the inputs 1/2/3 mentioned and translate that information into the existing input (which would then be hidden).

**Comment by czlee** [comment]
How about the following: Include in the context a list of debate-adjudicators for whom feedback has already been submitted. Using JavaScript, if the user tries to select one of those options (or another for the same round), show an alert telling them that they've already submitted one for that round.

Would that be enough, or does it need to be as involved as a two-page formset?

**Comment by philipbelesky** [comment]
Um, I think that would be fine, although would prefer the 1/2/3 prompt (implemented on a single page) as mentioned above as it makes the process slightly clearer/simpler. Although it could also be aided by having a similar prompt in terms of notifying people a submission already exists for that round.

**Comment by czlee** [comment]
Hmm, okay. I can see why the three-step prompt is clearer, it just seems like more than a front-end presentation thing to me; the back-end needs collate the relevant information so that the front-end knows how to filter things. If contrary to my intuition it really is a minimal change, that sounds fine.

Here's another idea for a patch: Add a field to the feedback form asking if the chair got rolled (or even if this adjudicator gave the oral adjudication). Check (in form validation) whether it's consistent with the adjudicator chosen. If not, raise a validation error. Actually, this isn't much better, if at all, just thought I'd throw the idea out there.

With the nice-to-have ideas I feel like we've already resigned to having to develop the adjudicator feedback system rigorously, though. Which is fine, I guess, it just seems risky in the long run.

**Comment by philipbelesky** [comment]
I think the checkbox validation idea would be a good fall back implementation in the case that the reworking of the inputs turns out to be arduous.

**Comment by tienne-B** [comment]
I'd be comfortable with closing this task with #1387, making the drop-down clearer with the shortening of the text, grouping by debate/round, and marking already submitted. What is suggested here seems too complicated to be worth doing, in my view, with the current work.

**Comment by philipbelesky** [comment]
Agree that the flow as outline is too complicated to be worth doing.
