### ISSUE TITLE
Use sockets for self checkin

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#832]
Using `POST` messages for self checkin has no broadcast for the updated status, causing the change to not be reflected in the checkin views. This also has the reverse consequence that changes in status through the checkins sheet will not be reflected in the landing page (if an event happens while the participant has the page loaded). This is less important though. Don't think it is crucial but for the personal page, the events feed should be filtered to only include events relating to the subject.

**Comment by philipbelesky** [comment]
The use of websockets themselves is not strictly required in order to broadcast an updated status. A POST message could do the same — it just needs to notify the relevant [consumer](https://channels.readthedocs.io/en/latest/topics/consumers.html) which then broadcasts the status.

In this case the `CheckInEventConsumer` should be notified in the original `POST`. If your interested in implementing this the code will be similar to that in `results/forms.py`:

```
                group_name = BallotResultConsumer.group_prefix + "_" + t.slug
                async_to_sync(get_channel_layer().group_send)(group_name, {
                    "type": "send_json",
                    "data": self.ballotsub.serialize_like_actionlog
                })
```

...but adapted to provide data in the same way that the `broadcast_checkin` method of `CheckInEventConsumer` does at present.

**Comment by tienne-B** [comment]
Thank you! I'll try.
