### ISSUE TITLE
Email Notification: Add additional information to ballot receipts

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#845]
Thanks to @tienne-B for his hard work on bringing this excellent new feature to life. I was wondering if it would be helpful to add some additional information to the {{ scores }} variable. 

![capture](https://user-images.githubusercontent.com/3196468/46149126-b1a83b00-c2bd-11e8-8d4f-1228af6535d5.PNG)

It might be useful to include the total scores and ranking win/lose as well. I think judges are more likely to notice an issue here than by reading the individual speaker scores. This may be low priority given the work it might take to develop different display formats or may have intentionally not been done.

I can think of different ways to do this but one could possibly be:

BP: 
1st - CG: Sacred Heart 2 (180)
2nd - CO: St Andrews 2 (170)
3rd - OG: Macleans 2 (160)
4th - OO: St Marys 1 (140)

WSDC:
Winner - Proposition: Germany (250)
Loser - Opposition: France (245)

**Comment by tienne-B** [comment]
Good points! It may also be useful to include the roles of each speaker (for people like me who don't remember names well) The ordering should be kept to maintain the order of the scoresheet, instead of being sorted by rank in my view.

What I have would look like:

OG: Macleans 2 (160 - 3rd)
- PM: Person A (80)
- MC: Person B (80)

_etc._

There are many things in this task: changing sides to abbreviations, adding rankings with team scores, and re-ordering teams and variables. All of this is generalizable to every format, and so the display is not a problem :) I'll have something out soon.

**Comment by 0zlw** [comment]
Cool! I agree, may be best to maintain the scoresheet format. Speaker roles sound good.
