### ISSUE TITLE
CSV API for adjudicators

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#911]
To support #910 there should be a list of basic adj information in terms of name, institution etc. This would allow the feedback list to refer to primary keys.

**Comment by nickdbush** [comment]
Would be more than happy to look into this if the issue is still looking for a maintainer

**Comment by tienne-B** [comment]
That would be great! Currently, there is a "stopgap" API to get basic adjudicator information and adjudicator feedback:
https://github.com/TabbycatDebate/tabbycat/blob/0892a21e239de490057fe2f35ffc869021456d51/tabbycat/adjfeedback/views.py#L825-L878
However it would be best to use the Django Rest Framework and create a stronger solution. What is already there should not either be taken as what is looked for, so don't feel bound by it.

A little discussion is what format to use, between CSV (or another delimiter) and JSON.

**Comment by nickdbush** [comment]
My thoughts exactly. I'm verging towards JSON as it has native interopability with JS, which is what the TabbyCat client is written in, which saves on importing large parsers into the final build.

What exactly is the use case for the adjudication API? Is it for people to be able to write their own clients to provide feedback, or is it supposed to be a read-only affair?

If we're going to expose a feedback API, would it make sense to also create (probably read-only) APIs for the other classes of information while we're at it? I personally think that this would be beneficial, as it would allow a wider range of use cases (for instance, check-in through other means, such as card swiping).

**Comment by philipbelesky** [comment]
Hey @nickdbush thanks for your interest in this issue. 

To elaborate on the context of API: the use it was developer was to provide adjudication cores with a means of writing their own logic for how feedback is translated into an adjudicators rating. Typically this would involve more complex considerations than what Tabbycat itself provides, e.g. increasing the weighting of feedback received from the CA team, tracking the velocity of feedback improvement, etc. There are probably better examples of 'advanced' metrics here but I don't recall them exactly. This use case only really comes up at very large tournaments with an adjudication core with the ability and need to create elaborate feedback tracking systems. To date this has only been used at WUDC and a handful of other majors. There is also an end point for bulk-uploading adj scores which is how such a system then is imported back into Tabbycat to affect allocations. 

The reason for choosing CSV in the first instance was quite deliberate, as the adjudication core we were working with had their feedback system written as a Google Sheet that used a mix of scripted logic and formula logic. A CSV export made the data very easy to import and easy to clean prior to importing. We probably would want to preserve that method, at least for this use case — it seems not uncommon for an adjudication core who have high levels of expertise in programming via spreadsheets but far less familiarity with web development. Maybe there are libraries for Django Rest that also allow for CSV end points so we could offer both that and JSON easily?

A read-only API for other information would be great. We use Django rest for a few client end points that are able to use Django's authentication, so allowing write access might also not be too difficult also.

**Comment by czlee** [comment]
Thanks for your interest, @nickdbush!

On CSV vs JSON: I agree with all of the above three comments. If I had to choose one, I'd choose CSV despite its drawbacks in flexibility and robustness, because in my experience the typical use case involves some CA team member doing something with a spreadsheet. But if someone wanted to write something more robust, or a third-party client that is generally available (as opposed to just for the author's own tournament), I'd want to encourage that and can see JSON being useful there.

In principle, if there's a proposal for a read-write API, I'm on board―with obvious provisos around authentication being done properly and so on. To give some idea of what's in my imagination: someone were to write a third-party client to do a more thorough job of adjudicator feedback than what we're willing to cover in Tabbycat, I'd probably expect them to pull information about adjudicators, teams and debates from Tabbycat, have all feedback submissions run _only_ on the third-party system (_i.e._ Tabbycat would know nothing about feedback), and then push _only_ the adjusted adjudicator scores to Tabbycat, once per round.

That's all very ambitious and ill-defined, though. Realistically, what gets implemented first should be just be whatever's wanted by whoever is going to use this next. In fact, for APIs in general, it'll be a lot easier to imagine once there's someone who is actually working on a project that would use a Tabbycat API. :slightly_smiling_face:

**Comment by nickdbush** [comment]
We can run both JSON and CSV endpoints easily, with simply a ```?format=json``` or ```?format=csv``` query appended to the endpoint. Working on the readonly APIs first to get a feel for the codebase and then will start working through the adjudicator results.

I'll spend some time writing up a very basic proposal of the API, and then we'll have something concrete to discuss and work around. I'm happy to chat with anybody who is looking to use this feature in production and work those considerations into the design.

**Comment by nickdbush** [comment]
I assume introducing a GraphQL endpoint would be beyond the scope of this issue?

**Comment by czlee** [comment]
We could ask on the Facebook group who's either done or has thought about doing something that would benefit from having an API? I know a few people have contacted either me or our Facebook Page with ideas that could benefit from it, but I don't know how far anyone would take their plans if the opportunity existed.

I don't know anything about GraphQL, and having just had a quick look I still don't know the answer to that question, sorry! I'd recommend starting with a view towards a project that will actually be used at a tournament, though―it's the fastest way to learn about the practical realities of putting this into action.

**Comment by philipbelesky** [comment]
When I reworked the allocation pages to use websockets and the Django Rest serialisers I considered a graphQL api but put it in the ‘too hard for now’ column. If you were keen to explore this further that would be great! The one concern would be performance if used on certain pages (like adj allocation) that pull down a pretty large set of data and require query optimisation. But if used as a general purpose API it sounds like it would be a super flexible option.

**Comment by nickdbush** [comment]
Would it be worth putting together a quick survery so we can gather feedback from people looking to put this into production? As tabbycat's data is very hierarchical, I think a GraphQL would probably be easiest for API consumers (saving on N+1 and all that), however it would also be pointless to work on changes which no actual implementations would benefit from.

**Comment by philipbelesky** [comment]
A survey sounds good. I thought this year’s wudc was going to make an app and wanted an API but I haven’t heard anything on that front.
