### ISSUE TITLE
Log and display ballot's country of origin

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#97]
At the point we are logging IP's (presumably to track waves of ballots submitted by the same person) it would probably be a good idea to also log the IP's location (to track obviously fraudulent submissions) , using an API such as http://freegeoip.net. Ideally both would also be shown in the admin UI somewhere. Probably not needed for Australs, although could be good if trivial to implement.

**Comment by czlee** [comment]
I was thinking about how one would do this. It's not desirable for machine-to-machine requests to block a Tabbycat server response, so either we would want to (a) get the client machine to use the freegeoip API, or (b) have Tabbycat populate IP address information in its own database (cache) on user submission or asynchronously.

But it turns out there's a Django contrib app available for this kind of thing:
https://docs.djangoproject.com/en/1.10/ref/contrib/gis/geoip2/

I think `gis` might be a little heavy, since it allows a much richer variety of geospatial applications. In which case, Django's geoip2 is just a wrapper for Maxmind's Python library, which we might just install instead:
https://geoip2.readthedocs.io/en/latest/

We could then avoid having to do HTTP requests from a Tabbycat server by using Maxmind's databases (they have free ones licensed under CC-by-SA 4.0). But that would require us either to include the binary file in the Tabbycat repo, or to add installation instructions for it (and somehow make it optional, since not all sites will use online submissions). Since the databases are updated every month, neither of these seem like desirable options, though maybe updating it once per release cycle isn't so bad.

Using a web service seems the least-maintenance option then, in which case we'd probably want to have Tabbycat keep a geo-information cache that gets populated asynchronously. This seems nontrivial, but might be fun, I guess?

**Comment by philipbelesky** [comment]
Hmm, I don't think this is of much value given unique-URLs seem to be the go-to solution for major tournaments where fraud prevention is key. That said if you are keen to have a play with this I think its better to go for minimise impact and maintainability of any changes. Which is to say an extra HTTP request for a feedback/score submission doesn't sound that bad. Is the proposed cache just a record of IPs-to-locations for IPs that have already been looked up? Or is it caching the the IP ranges that correspond to geographies?

**Comment by czlee** [comment]
Yeah, I don't think this feature would be life-changing unless we include automatic fraud detection, _i.e._ something that not only tracked IP addresses but actively alerted users if something looked untoward. That said I think unique URLs are attacking a different problem—prevention and detection are different things. Specifically, geolocation won't prevent a URL compromise, and if someone compromises a unique URL, then IP address tracking would still give us a hope of detecting it.

It's not a great hope, to be honest—any URL compromises are likely to be from the same country (indeed, the same campus). What we'd really be detecting here would be trolls, or I guess cheats doing things from afar. Probably the better thing would be to detect by session (or by machine but I don't think that's possible), I guess.

If IP addresses are cached then they'd just be by IP address, unless there's a way to store IP address ranges that doesn't break the encapsulation in the API (they normally take single IP addresses in requests, right?). Presumably each IP address will submit many forms, and pages will be loaded many times, so storing geolocation information for each IP address should reduce the number of requests to the API by quite a bit over the life of a tournament.

**Comment by czlee** [comment]
Bottom line is it's nontrivial to implement though, so if you're of the view that it won't add very much then I'm inclined to label it won't-fix. We don't actually analyse IP addresses to detect fraud at the moment, I think the reason I put them in was so that after the fact we could investigate it if we heard something, rather than an expectation someone would catch them in real time.

**Comment by tienne-B** [comment]
Closing as wontfix; this would be a lot of work/expensive while the gain is minimal. Most use private URLs, and suspicious submissions don't really lead to "investigations" with the time constraints.
